feature: add Search Input logic #1730
intive/patronage22_poznan_js pull request #100
Opened 2022-03-30 19:58 UTC by marcelina-hasiak

2022-03-30 22:30 UTC, rast-mk1 commented
Looks like a whole bunch of less popular movies don't have backdrops. Maybe it would be better to use posters in search result grid instead?
Lack of backdrops will be a problem for `MovieHero`, but, it could have some default image if backdrop is not there.

2022-03-30 22:55 UTC, rast-mk1 requested changes

2022-03-30 22:55 UTC, rast-mk1 commented on app/components/UI/MovieGrid/index.js
> +    </StyledMovieGrid>
`MovieCard` should be using `id` to build `href` to specific movie page.
![obraz](https://user-images.githubusercontent.com/56893415/160944079-26f2d3f0-b16d-4536-bccc-1fd0e56a8f70.png)

2022-03-31 13:45 UTC, weronika299 reviewed
Could you pull the latest develop? Now you have changes from HomePage as well. If the PR includes only your changes, it will be more transparent.

2022-03-31 15:20 UTC, marcelina-hasiak commented
I'm closing this PR, please visit: https://github.com/intive/patronage22_poznan_js/pull/103 to continue review.

2022-03-31 15:20 UTC, marcelina-hasiak commented
I'm closing this PR, please visit: https://github.com/intive/patronage22_poznan_js/pull/103 to continue review.

2022-03-31 15:20 UTC, closed without merging