fix: clickable buttons in mobile view #2094
intive/patronage22_poznan_js pull request #108
Opened 2022-04-02 19:40 UTC by weronika299

2022-04-02 20:53 UTC, hiimsagan approved these changes
Is woorking, but btw sign-up should be center on mobiles 
![Zrzut ekranu 2022-04-02 225055](https://user-images.githubusercontent.com/83120643/161400846-4c964eea-f6c3-4a30-8c39-63f1abf0b562.png)
?

2022-04-04 11:15 UTC, lenasokolova commented on app/components/Pages/AuthPageContainer/AuthPageContainer.styles.js
>    color: white;
I believe it's better to use #fff instead of words like "white" but it's a little thing :)

2022-04-04 22:17 UTC, wlechowicz requested changes
I can't accept this.
1. the span you're trying to affect is part of next/Image, therefore this is a hack, not a fix
2. we should never need `!important` with styled-components, another sign you're trying to do something fishy

Did you try the alternative solution I proposed, with just a background-image instead of next/Image and using two images, small blur and the actual image at once in single background-image statement?
`background-image: url('actual-image'), url('blur-image');` it goes top to bottom from left to right, so the first one will be on top, so the blur will show through as the actual image is loading.

2022-04-05 10:32 UTC, weronika299 commented
> I can't accept this.
> 
> 1. the span you're trying to affect is part of next/Image, therefore this is a hack, not a fix
> 2. we should never need `!important` with styled-components, another sign you're trying to do something fishy
> 
> Did you try the alternative solution I proposed, with just a background-image instead of next/Image and using two images, small blur and the actual image at once in single background-image statement? `background-image: url('actual-image'), url('blur-image');` it goes top to bottom from left to right, so the first one will be on top, so the blur will show through as the actual image is loading.

Okay, you're right. Yes, I tried this solution, but I think I did something wrong because it didn't work for me, but I will try again. Thank you!

2022-04-06 18:22 UTC, wlechowicz approved these changes
Let's leave it as is.
Doesn't seem to work for me, the placeholder image shows up only after the big one is downloaded (disabled caching with throttled network). Perhaps it would have to be split into 2 separate containers, one on top of the other. Or maybe just converting the JPEG to a progressive one would fix this once and for all.

2022-04-06 19:14 UTC, merged