feat: add mylist carousel #1902
intive/patronage22_poznan_js pull request #111
Opened 2022-04-04 12:09 UTC by weronika299

2022-04-04 13:11 UTC, rast-mk1 approved these changes
Looks good. Not sure, if carousel for `myList` should have title "MyList" but rather"My List" or something else

2022-04-04 13:15 UTC, weronika299 commented
> Looks good. Not sure, if carousel for `myList` should have title "MyList" but rather"My List" or something else

Yes, you're right. I didn't notice it. I will corect it. Thanks!

2022-04-04 13:36 UTC, rast-mk1 commented
One more thing: probably would be better, if my List is not rendered with 0 MovieCards when it is empty: 
![obraz](https://user-images.githubusercontent.com/56893415/161555843-781155e7-5398-4d33-833c-03287a9af370.png)

2022-04-04 17:12 UTC, lenasokolova approved these changes

2022-04-04 21:37 UTC, wlechowicz requested changes

2022-04-04 21:37 UTC, wlechowicz commented on pages/index.js
> +    const myList = await getMyList({ session });
You shouldn't do this here, `getMyList` should pull the session from req on its own, so you would just do `getMyList(req);`  Must have fallen in between the cracks? @rast-mk1 
I guess let's leave this as is and let's change this once `getMyList` is fixed.

2022-04-04 21:37 UTC, wlechowicz commented on app/components/Pages/HomePage/index.js
> +            )}
```suggestion
            <Link href={id === 0 ? '/mylist' : `/category/${id}`} passHref>
              <CarouselHeader>{name}</CarouselHeader>
            </Link>
```
Additional notes:
1. CarouselHeader does not accept `categoryId` prop
2. CarouselHeader should extend `a`, not `p`. Otherwise, it needs to be wrapper in `<a>` or else the link doesn't work properly.

2022-04-04 21:37 UTC, wlechowicz commented on pages/index.js
> +    const listOfCarousels = [myListCategory, popularCategory, ...listOfCategories];
Filter out the whole carousel if My List is empty, for example like this:
```suggestion
    const listOfCarousels = myList?.length
      ? [{ id: 0, name: 'My List', listOfMovies: myList }, popularCategory, ...listOfCategories]
      : [popularCategory, ...listOfCategories];
```

2022-04-05 08:42 UTC, rast-mk1 commented on pages/index.js
> +    const myList = await getMyList({ session });
Seems like it did.

2022-04-06 18:25 UTC, wlechowicz approved these changes

2022-04-06 19:09 UTC, merged