feat: edit avatar backend #1928
intive/patronage22_poznan_js pull request #115
Opened 2022-04-07 00:24 UTC by rast-mk1

2022-04-08 05:02 UTC, hiimsagan approved these changes
Looks good

2022-04-08 10:56 UTC, wlechowicz requested changes

2022-04-08 10:56 UTC, wlechowicz commented on pages/api/users/avatar/[id].js
> +    const session = verifyJwtInRequest(req);
Should be using getSession from "next-auth/react" instead.

2022-04-08 10:56 UTC, wlechowicz commented on pages/api/users/avatar/[id].js
> +    const user = (await db.collection('users').find(query, { limit: 1 }).toArray())[0];
`.findOne` instead of `.find` with limit 1.

2022-04-08 10:56 UTC, wlechowicz commented on pages/api/users/avatar/[id].js
> +    if (Number.isInteger(newAvatarId)) {
Validation of the input param should be done early to exit early if it's bad, now I can spam the API with rubbish avatar Ids and you will waste resources because you connect to DB and search for users without checking the id first.

2022-04-11 13:11 UTC, weronika299 approved these changes
I think that it looks good.

2022-04-15 14:27 UTC, rast-mk1 commented on pages/api/users/avatar/[id].js
> +        return res.status(404).json({ error: 'Cannot find avatar with given id. ' });
Note to self: Checking `newAvatarId` against `avatars` should be done before connecting to DB - fix that.

2022-05-04 11:31 UTC, wlechowicz approved these changes

2022-05-04 11:33 UTC, merged