feat: add myList page
intive/patronage22_poznan_js pull request #118
Opened 2022-04-09 12:39 UTC by lenasokolova

2022-04-10 23:39 UTC, rast-mk1 commented on pages/mylist.js
> +}
Try with these changes:
```suggestion
export async function getServerSideProps({ req }) {
  try {
    const myList = await getMyList(req);

    return {
      props: {
        moviesData: myList ? myList : [],
      },
    };
  } catch (e) {
    console.error(e);
    return { props: {} };
  }
}
```

2022-04-12 15:18 UTC, rast-mk1 approved these changes

2022-04-13 16:27 UTC, weronika299 commented on app/components/Pages/MyListPage/index.js
> +  console.log(moviesData);
Could you remove this console.log?

2022-04-13 16:37 UTC, weronika299 commented on app/components/Pages/MyListPage/index.js
> +    <>
Is this empty tag necessary?

2022-04-13 17:35 UTC, lenasokolova commented on app/components/Pages/MyListPage/index.js
> +    <>
you're right. Here's only one parent so JSX tag is redundant here :)

2022-04-13 17:37 UTC, lenasokolova commented on app/components/Pages/MyListPage/index.js
> +          <MyListTitle></MyListTitle>
oops I'll fix that

2022-04-13 22:04 UTC, marcelina-hasiak requested changes

2022-04-13 22:04 UTC, marcelina-hasiak commented on app/components/Pages/MyListPage/index.js
> +  const [searchQ, setSearchQ] = useState('');
const [query, setQuery] = useState('') <- I would rename these two

2022-04-13 22:04 UTC, marcelina-hasiak commented on pages/mylist.js
> +        moviesData: myList ? myList : [],
Our handler already returns empty array if there's no list. Check api/myList.js file

2022-04-14 07:23 UTC, lenasokolova commented on pages/mylist.js
> +        moviesData: myList ? myList : [],
yeah, you're right! :)

2022-05-04 11:25 UTC, merged