feat: home page roadblock #1745
intive/patronage22_poznan_js pull request #123
Opened 2022-04-13 15:53 UTC by weronika299

2022-04-13 17:58 UTC, lenasokolova commented on app/components/Pages/StartPage/StartPage.styles.js
> +`;
don't you think SignUpLink should look more like a button? 
![image](https://user-images.githubusercontent.com/62836941/163241607-b40c9c59-303a-4985-bba6-3843f00c61ae.png)

2022-04-13 19:37 UTC, rast-mk1 requested changes
1. There is second scrollbar when window size is reduced. Also, text goes to left side.
![obraz](https://user-images.githubusercontent.com/56893415/163255648-49efc83b-8b9b-4d4f-96f0-c5fc87bda1eb.png)
2. There is horizontal scrollbar when browser is set to imitate smartphone.
![obraz](https://user-images.githubusercontent.com/56893415/163256473-07fcbace-ebe7-47ef-ba07-267a7018958c.png)

2022-04-13 19:37 UTC, rast-mk1 commented on app/components/Pages/StartPage/index.js
> +              Register now in inTiVi now and enjoy watching the latest movies.
Word 'now' is repeated.

2022-04-13 20:08 UTC, weronika299 commented on app/components/Pages/StartPage/index.js
> +              Register now in inTiVi now and enjoy watching the latest movies.
> 1. There is second scrollbar when window size is reduced. Also, text goes to left side.
>    ![obraz](https://user-images.githubusercontent.com/56893415/163255648-49efc83b-8b9b-4d4f-96f0-c5fc87bda1eb.png)
> 2. There is horizontal scrollbar when browser is set to imitate smartphone.
>    ![obraz](https://user-images.githubusercontent.com/56893415/163256473-07fcbace-ebe7-47ef-ba07-267a7018958c.png)

This horizontal scrollbar appears below 375px width. I removed second vertical scrollbar but text on the left side on tablets is intentional because on tablets  we have more free space on the left side than on the right side when we use this background image.

2022-04-13 20:08 UTC, weronika299 commented
> 1. There is second scrollbar when window size is reduced. Also, text goes to left side.
>    ![obraz](https://user-images.githubusercontent.com/56893415/163255648-49efc83b-8b9b-4d4f-96f0-c5fc87bda1eb.png)
> 2. There is horizontal scrollbar when browser is set to imitate smartphone.
>    ![obraz](https://user-images.githubusercontent.com/56893415/163256473-07fcbace-ebe7-47ef-ba07-267a7018958c.png)

This horizontal scrollbar appears below 375px width. I removed second vertical scrollbar but text on the left side on tablets is intentional because on tablets we have more free space on the left side than on the right side when we use this background image.

2022-04-13 21:33 UTC, marcelina-hasiak requested changes
Small adjustment needed, apart from that good job ;)

2022-04-13 21:33 UTC, marcelina-hasiak commented on app/components/Pages/StartPage/StartPage.styles.js
> +export const WelcomeHeader = styled.p`
If it's header wrap the content with catchy H1 tag ;)

2022-04-13 21:48 UTC, weronika299 commented on app/components/Pages/StartPage/StartPage.styles.js
> +`;
Okay, I will change it.:)

2022-04-13 21:48 UTC, weronika299 commented on app/components/Pages/StartPage/StartPage.styles.js
> +export const WelcomeHeader = styled.p`
Okay, I will change it. Thanks!

2022-04-13 22:57 UTC, rast-mk1 approved these changes

2022-04-14 19:37 UTC, lenasokolova approved these changes
in my opinion, now it's a lot better :) nicely done!

2022-04-14 20:12 UTC, rast-mk1 approved these changes

2022-04-15 15:11 UTC, weronika299 commented
> in my opinion, now it's a lot better :) nicely done!



> in my opinion, now it's a lot better :) nicely done!

Yes, you're right ;)

2022-04-15 15:11 UTC, weronika299 commented
> in my opinion, now it's a lot better :) nicely done!



> in my opinion, now it's a lot better :) nicely done!

Yes, you're right ;)

2022-05-04 11:07 UTC, merged