feat: change username view
intive/patronage22_poznan_js pull request #124
Opened 2022-04-13 17:02 UTC by lenasokolova

2022-04-13 19:25 UTC, rast-mk1 commented
What do you think about having `cursor: pointer` when hovering over username?

2022-04-13 21:25 UTC, marcelina-hasiak requested changes

2022-04-13 21:25 UTC, marcelina-hasiak commented on app/components/Account/index.js
> +          </section>
Hmmm... If it's possible I'd omit logic nesting it's quite unreadable, what's more I see duplicated section with EditUsername perhaps you'll fing a way to improve it ;)

2022-04-13 21:25 UTC, marcelina-hasiak commented on app/components/Account/index.js
> +                  {user.name && <Username>{user.name}</Username>}
Pass callback here just like you did inside PencilIcon. But wait, do you need both event handlers?

2022-04-14 15:05 UTC, rast-mk1 approved these changes

2022-05-04 11:24 UTC, merged