Header and navBar
intive/patronage22_poznan_js pull request #19
Opened 2022-02-04 13:39 UTC by hiimsagan

2022-02-08 15:22 UTC, danielmajewski commented on app/components/Header/Nav.js
> +const SingleA = ({ name, link }) => {
use enter after imports

2022-02-08 15:22 UTC, danielmajewski commented on app/components/Header/Nav.js
> +        <StyleI href={link}>
this is not StyleI but styled component. Name it what is does then it's more readable e.g.: `NavigationLink`, same thing below

2022-02-08 15:22 UTC, danielmajewski commented on app/components/Header/headerStyle.js
> +background-color: rgba(30,30,41,0.5);
use indent

2022-02-08 15:22 UTC, danielmajewski commented on app/components/Header/headerStyle.js
> +const NavBar = styled.header`
Use full names: `NavigationBar`, same below

2022-02-08 15:22 UTC, danielmajewski commented on app/components/Header/headerStyle.js
> +export { NavBar, MainNavBar, LogoName, SecondNavBar, ExploreMore, MobileFormUl, LinkStyle, StyleI, UserImg, DesctoFormUl, DesctopLinkStyle }
make exports before declarations

2022-02-08 15:22 UTC, danielmajewski commented on app/components/Header/index.js
> +                    <ExploreMore onClick={() => setMoblieMenu(!showMoblieMenu)} >{mobileMenu}</ExploreMore>
What is ExploreMore? Teaser? Title?

2022-02-08 15:22 UTC, danielmajewski commented on app/components/Header/headerStyle.js
> +background-color:black ;
use indent, space and remove space at the end
    background-color: black;

2022-02-08 15:22 UTC, danielmajewski commented on app/components/Header/headerStyle.js
> +    desctop: `@media(min-width:1024px)`,
typo desktop, use spaces, extract resotions breakpoints to seperate file

2022-02-08 15:22 UTC, danielmajewski commented on app/components/Header/headerStyle.js
> +const ExploreMore = styled.span`
please do not use spans like that. Why won't you use p instead?

2022-02-09 14:18 UTC, hiimsagan commented on app/components/Header/Nav.js
> +import { DesctoFormUl, MobileFormUl, LinkStyle, StyleI, DesctopLinkStyle } from "./headerStyle"
I will try use single quote

2022-02-10 22:07 UTC, wlechowicz requested changes

2022-02-10 22:07 UTC, wlechowicz commented on app/components/Header/headerStyle.js
> +export const MobileFormUl = styled.ul`
`MobileFormUl` has 2 issues for me, "Form" is confusing since it's not a form, "Ul" should be "List" instead.

2022-02-10 22:07 UTC, wlechowicz commented on app/components/Header/headerStyle.js
> +export const DesktopFormUl = styled.ul`
Same problems as MobileFormUl.

2022-02-10 22:07 UTC, wlechowicz commented on app/components/Header/index.js
> +  const [showMobileMenu, setMobileMenu] = useState(false);
Boolean variables should typically start with 'is', like `isMobileView` or `isMobileMenuVisible` in this case.

2022-02-10 22:07 UTC, wlechowicz commented on app/components/Header/index.js
> +            style={{ fontSize: '25px', paddingBottom: '5px', color: 'white' }}
And make this a styled component while you're at it.

2022-02-10 22:07 UTC, wlechowicz commented on app/components/Header/Nav.js
> +          <DesktopLinkStyle key={navigationItem.name}>
Clever way of making a key, but not a safe one. You have spaces and special characters in the names, not well suited for keys. Best way around this is adding `id` field to each link and using that as keys, alternatively you can do a `.replaceAll(' ', '-')` here but the issues of special chars like & remains.

2022-02-14 01:17 UTC, wlechowicz approved these changes

2022-02-14 01:17 UTC, wlechowicz commented
LGTM

2022-02-14 01:19 UTC, merged