Feature/p2022 613 create footer
intive/patronage22_poznan_js pull request #20
Opened 2022-02-04 16:10 UTC by weronika299

Icons will be added in a separate subtask P2022-734, because I'm waiting for a ticket P2022-610 (Add font awesome icons to project).

2022-02-04 21:21 UTC, marcelina-hasiak commented on app/components/Footer/index.js
> +            </LinksList>
It's quite a long list of <LinkStyle> repeated component. According to DRY principle, perhaps it would be better to gather all the data connected to links in one object/array and then iterate through  it. Check it out: https://reactjs.org/docs/lists-and-keys.html

2022-02-04 21:21 UTC, marcelina-hasiak commented on app/components/Footer/index.js
> +`;
I had the same in my previous PR. Just add an empty line (+73) ;)

2022-02-04 21:21 UTC, marcelina-hasiak commented on app/components/Footer/index.js
> +    color: grey;
Isn't a better way to declare colors with rgb or hex code? If they're the same as on Netflix site it'd be easier to replace them across the whole app when we get final designs.

2022-02-04 21:21 UTC, marcelina-hasiak commented on app/components/Footer/index.js
> +    bottom: 0;
Default `position` property is `static`, so `bottom: 0` does nothing. 
To put footer exactly on the bottom of the page some styling property should be added also to its parent.

2022-02-04 21:21 UTC, marcelina-hasiak commented on app/components/Footer/index.js
> +export const FooterWrapper = styled.div`
By declaring `FooterWrapper` as div we've lost semantic tag which is `footer`

2022-02-08 15:04 UTC, danielmajewski commented on app/components/Footer/index.js
> +    @media (max-width: 992px) {
can you put resolution breakpoint into separate file?

2022-02-08 15:04 UTC, danielmajewski commented on app/components/Footer/index.js
> +    color: rgb(94, 93, 93);
I think that HEX colors are enough for us.

2022-02-08 15:04 UTC, danielmajewski commented on app/components/Footer/index.js
> +        {listItems}
indent

2022-02-08 15:06 UTC, danielmajewski commented on app/components/Footer/index.js
> +import styled from "styled-components";
use ' instead of "

2022-02-08 15:06 UTC, danielmajewski commented on app/components/Footer/index.js
> +const links = ['Audio and Subtitles', 'Audio Description', 'Help Center', 'Gift Cards', 'Media Center', 'Investor Relations', 'Jobs', 'Terms of Use', 'Privacy', 'Legal Notices', 'Cookie Preferences',
```suggestion
const mockLinks = [
    'Audio and Subtitles',
    'Audio Description',
    'Help Center',
    ...
```

2022-02-09 17:11 UTC, wlechowicz requested changes
Prettier will fix the formatting issues automatically, so not commenting on those.

2022-02-09 17:11 UTC, wlechowicz commented on app/components/Footer/index.js
> +      <Item key={index} value={link} />
Using array index as `key` is and anti-pattern. You can read more [here](https://pl.reactjs.org/docs/lists-and-keys.html#keys) and [here](https://medium.com/wesionary-team/using-index-as-a-key-is-an-anti-pattern-in-react-8e5db3aea3a9). Your `mockLinks` should be a list of objects, each containing a key, a display string and an href at minimum. If you don't want to play around with fake hrefs, then don't use `<a>` at all, just use a `<span>` with styling. An `<a>` without `href` is a no-no.

2022-02-09 17:11 UTC, wlechowicz commented on app/components/Footer/index.js
> +        <FontAwesomeItem> <FontAwesomeIcon icon= { faYoutube } /> </FontAwesomeItem>
That's a lot of the same code repeated, enough to make it a small local component that takes one prop and saves you from the copy and paste.

2022-02-09 17:11 UTC, wlechowicz commented on app/components/Footer/breakpoints.js
> +};
These should be common for the whole app, not footer specific. Also the 425 breakpoint seems unnecessary. Tablet should be the only one we need for mobile-first approach.

2022-02-09 17:11 UTC, wlechowicz commented on app/components/Footer/index.js
> +      <p style={{ fontSize: "0.8rem", marginLeft: "2.40rem", marginTop: "2rem" }}>© 2022 InTiVi</p>
Make this a styled component.

2022-02-09 17:11 UTC, wlechowicz commented on app/components/Footer/index.js
> +export const FontAwesomeItem = styled.li`
Doesn't seem like anything about this component makes it Font Awesome specific, so a more generic name would be better, like IconWrapper.

2022-02-09 17:11 UTC, wlechowicz commented on app/components/Footer/index.js
> +export const IconWrapper = styled.ul`
`IconList` would make more sense, since it's a list.

2022-02-09 22:55 UTC, rast-mk1 commented on app/components/Footer/index.js
> +`;
Could you make it that not the entire list item, but rather just the caption inside it is underlined and with cursor: pointer on hover?

2022-02-10 17:33 UTC, rast-mk1 commented on app/components/Footer/index.js
> +`;
Sure, that's also fine.

2022-02-10 19:55 UTC, hiimsagan commented on app/components/Footer/index.js
> +  ];
Perhaps i will be better to have that in other file ? @wlechowicz @danielmajewski

2022-02-10 19:55 UTC, hiimsagan commented on app/components/Footer/index.js
> +  ];
Same think to style components ?

2022-02-10 21:44 UTC, weronika299 commented on app/components/Footer/index.js
> +  ];
Ok, I will fix it. Should I make the same with styled components?

2022-02-10 21:51 UTC, wlechowicz commented on app/components/Footer/index.js
> +  ];
Yes, commented on that in my review.

2022-02-11 20:15 UTC, weronika299 commented on app/components/Footer/index.js
> +  ];
Ok, I will correct it

2022-02-13 23:34 UTC, wlechowicz commented on pages/index.js
> -      <footer className={styles.footer}>(c) intive 2022</footer>
Never mind, it's used through the Layout component!

2022-02-16 15:35 UTC, hiimsagan approved these changes
Well done

2022-02-20 21:52 UTC, wlechowicz approved these changes

2022-02-20 21:53 UTC, wlechowicz commented
LGTM

2022-02-20 22:03 UTC, merged