Feature/P2022-611-video-section
intive/patronage22_poznan_js pull request #22
Opened 2022-02-06 15:34 UTC by wolnio

2022-02-06 15:45 UTC, wolnio commented
URL addres for this feature: /banner/video-section

2022-02-07 10:41 UTC, danielmajewski commented on pages/banner/video-section.js
> +      <Wrapper imgLink={"https://wallpaperaccess.com/full/2191678.jpg"}>
can you download this image as our internal not external source? So we could just import it inside our project?

2022-02-07 10:41 UTC, danielmajewski commented on app/components/Banner/index.js
> +  };
isMute should anser only Yes or No, so use as boolean values only if prefix `is` for variables.

```suggestion
  const [isMute, setMute] = useState(true);

  const toggleMute = () => setMute(!isMute);
```

2022-02-09 12:26 UTC, wlechowicz commented
Not sure why checks aren't running on this, I reverted my dummy commits that were supposed to trigger them.

2022-02-09 12:28 UTC, wlechowicz commented
Oh I know, @wolnio please pull in develop onto this branch and push the merged changes to origin.

2022-02-10 21:36 UTC, wlechowicz requested changes
1. Rename the component from Banner to MovieHero or FeaturedVideo, Banner is misleading
2. Split up the components into separate files, for example `app/components/MovieHero/MuteIcon.js`, `MovieHero/PlayIcon.js` etc which get imported by the main component in index.js. These icons will likely get reused in the future so might get extracted into common components later.

2022-02-10 21:36 UTC, wlechowicz commented on pages/banner/video-section.js
> +        <Contents flexDir={"column"}>
Does it make sense to have the flex-direction configurable like this? Setting it to `row` doesn't seem to work well anyway, since title is touching the button.

2022-02-10 21:36 UTC, wlechowicz commented on pages/banner/video-section.js
> +import { Wrapper, Contents, Title, Media } from "components/Banner";
This should be just one component that takes a movie object through props and does the rest internally. If I want to use a movie hero component, I want just one component, I don't want to spell out the whole structure inside (Contents, Title, Media).

2022-02-13 23:37 UTC, wlechowicz approved these changes

2022-02-14 00:53 UTC, wlechowicz commented
LGTM

2022-02-14 11:43 UTC, merged