Feature/P2022-152-video-carousel
intive/patronage22_poznan_js pull request #23
Opened 2022-02-07 09:57 UTC by lenasokolova

Has one problem with the carousel - can't make it stop scrolling (or get back to the first image) after it reached the end of the carousel and it's nothing to be shown. Basically, I can't come up with an idea of what it has to depend on.

2022-02-18 14:03 UTC, hiimsagan requested changes

2022-02-20 09:35 UTC, lenasokolova commented on app/components/Carousel/CarouselStyle.js
> +);
You're right :) CarouselItem has already moved to the index.js

2022-02-20 09:37 UTC, lenasokolova commented on app/components/Carousel/CarouselStyle.js
> +export const CarouselItemInner = styled.div`
Since `CarosuelItem` has moved to the `index.js`, `CarouselItemWrapper` needs to be exported.

2022-02-20 09:43 UTC, lenasokolova commented on app/components/Carousel/index.js
> +  // TODO: czy da się reagować tylko na zmianę rozmiaru samego CarouselOuter zamiast window?
Thinking of it, I'm not sure about it now. As isn't it better to check the window width instead of the `CarouselOuter` width in order to display it properly on mobile / tablet / desktop?

2022-02-20 09:46 UTC, lenasokolova commented on app/components/Carousel/moviesData.js
> +export default Movies;
I think it could stay here, bc it's related to the data more than a functionality of the `Carousel `component. Carousel's mapping through the array in `index.js`. Why do you think it's better to move it to the index.js also?

2022-02-21 19:05 UTC, wlechowicz commented on app/components/Carousel/moviesData.js
> +export default Movies;
This is just a mock to preset the carousel and give it some data so it can stay as a page for now, later would be deleted. If there's a story for the carousel that gives it data, then we can remove this. Also all page names should use kebab-case so movie-data.js

2022-02-21 19:13 UTC, wlechowicz commented on app/components/Carousel/moviesData.js
> +export default Movies;
Sorry, wrong file. But the point stands, this should be a part of the test page only.

2022-02-22 19:49 UTC, weronika299 commented on app/components/Carousel/index.js
> +      >
Maybe better to do this as a styled component?

2022-02-22 21:45 UTC, MS151994 requested changes
Rename: 
app/components/Carousel/carousel-style.js -> app/components/Carousel/carousel.style.js

2022-02-22 21:45 UTC, MS151994 commented on app/components/Carousel/carousel-style.js
> +  right: ${(props) => (props.right === true ? 0 : 'auto')};
Suggested change:
`left: ${({left})}=>(left ? 0 : 'auto')};`

2022-02-22 21:45 UTC, MS151994 commented on app/components/Carousel/movies-data.js
> +];
Maybe can move this to /lib/carousel/mock ?

2022-02-23 07:39 UTC, lenasokolova commented on app/components/Carousel/index.js
> +      >
You're right. Already done it :)

2022-02-26 15:51 UTC, weronika299 requested changes

2022-02-26 15:51 UTC, weronika299 commented on app/components/Carousel/CarouselStories/index.js
> +// ];
Will you need it here later?

2022-02-26 15:51 UTC, weronika299 commented on app/components/Carousel/Carousel.styles.js
> +export const Button = styled.button`
Button sounds like default Button. Maybe change name to for example NavButton or something like that?

2022-02-26 15:51 UTC, weronika299 commented on app/components/Carousel/NavButtonStories/NavButton.styles.js
> +  color: white;
You should adjust background-color and color to stories  and the same in Carousel style for example:  background-color:  ${({ backgroundColor }) => backgroundColor || 'rgb(0, 0, 0, 0.2)'}

2022-02-26 16:52 UTC, rast-mk1 commented on app/components/Carousel/index.js
> +  // TODO: czy da się reagować tylko na zmianę rozmiaru samego CarouselOuter zamiast window?
Maybe `ResizeObserver` would be of use in here.

2022-02-26 16:55 UTC, rast-mk1 commented on app/components/Carousel/index.js
> +      }
Could import these breakpoints from `app/consts/mediaQueries.js`.

2022-02-26 16:58 UTC, rast-mk1 commented on app/components/Carousel/index.js
> +    const foo = () => {
`foo` name doesn't really explain it's purpose.

2022-02-26 17:07 UTC, rast-mk1 commented
Do you need both `index.js` and `Carousel.styles.js` inside `Carousel` and then also in `CarouselStories` folders?

2022-02-27 09:51 UTC, lenasokolova commented on app/components/Carousel/CarouselStories/index.js
> +// ];
will delete these! :)

2022-02-27 09:54 UTC, lenasokolova commented on app/components/Carousel/CarouselStories/Carousel.stories.js
> +];
> Rename: app/components/Carousel/carousel-style.js -> app/components/Carousel/carousel.style.js

it's already changed :)

2022-02-27 10:02 UTC, lenasokolova commented on app/components/Carousel/CarouselStories/index.js
> +// ];
right, I'll delete it

2022-02-27 10:16 UTC, lenasokolova commented on app/components/Carousel/Carousel.styles.js
> +export const Button = styled.button`
yeah, agree, that makes sense!

2022-02-27 10:38 UTC, lenasokolova commented on app/components/Carousel/NavButtonStories/NavButton.styles.js
> +  color: white;
right, done it already and now it works :) Thx!

2022-02-27 10:46 UTC, lenasokolova commented on app/components/Carousel/carousel-style.js
> +  right: ${(props) => (props.right === true ? 0 : 'auto')};
you're right, it makes sense! :)

2022-02-27 22:07 UTC, rast-mk1 requested changes

2022-02-27 22:07 UTC, rast-mk1 commented on app/components/Carousel/NavButtonStories/index.js
> +};
```suggestion
NavButton.propTypes = {
  handleClick: PropTypes.func,
  backgroundColor: PropTypes.string,
  type: PropTypes.oneOf(['chevron-left', 'chevron-right']),
};
```
Changes in line 22 enables checkbox for left and right chevrons in Storybook.

2022-02-28 17:50 UTC, lenasokolova commented on app/components/Carousel/NavButtonStories/index.js
> +};
nice one, this one is better

2022-02-28 17:54 UTC, lenasokolova commented on app/components/Carousel/NavButtonStories/NavButton.stories.js
> +};
everything work now :)

2022-02-28 17:54 UTC, lenasokolova commented on app/components/Carousel/CarouselStories/Carousel.stories.js
> +};
I'll check it once again. It needs changes for sure

2022-02-28 18:05 UTC, rast-mk1 commented on app/components/Carousel/CarouselStories/Carousel.stories.js
> +];
So let's import it from `mockData.js` now :)

2022-02-28 19:01 UTC, rast-mk1 commented on app/components/Carousel/NavButtonStories/NavButton.stories.js
> +};
Not yet :) 
inside `NavButtonStories/index.js` remove `color="#fff"` from `<Icon />` - this forces white color on your chevron icons
and add `color: PropTypes.string,` inside `NavButton.propTypes` so Storybook shows string in desciption

2022-02-28 22:40 UTC, marcelina-hasiak requested changes

2022-02-28 22:40 UTC, marcelina-hasiak commented on app/components/Carousel/CarouselStories/Carousel.stories.js
> +};
1. You have to style Carousel depending on passed props (wrap, direction, overflow, spacing - this one needs some more adjustments), just like you did in NavButtons - it works good there ;)
2. numberOfChildren seems to work now, but shouldn't you pass number value as you declared it as a number type?   
```
argTypes: {
    numberOfChildren: { type: 'number', defaultValue: 5 },
  },
```

2022-02-28 22:40 UTC, marcelina-hasiak commented on app/components/Carousel/NavButtonStories/NavButton.styles.js
> +  right: ${({ right }) => (right ? 0 : 'auto')};
```
  left: ${(props) => props.left && '0'};
  right: ${(props) => props.right && '0'};
```
Perhaps this change above would be enough ;) You can also use destructuring if you like:
```
  left: ${({left}) => left && '0'};
  right: ${({right}) => right && '0'};
```

2022-03-01 13:45 UTC, wlechowicz commented on app/components/Carousel/NavButtonStories/NavButton.styles.js
> +  right: ${({ right }) => (right ? 0 : 'auto')};
👍 for destructuring
👎 for && - if `props.left` is false, then `left: false;` will be the result

2022-03-01 16:21 UTC, marcelina-hasiak commented on app/components/Carousel/NavButtonStories/NavButton.styles.js
> +  right: ${({ right }) => (right ? 0 : 'auto')};
Now I see my solution proposal is bug vulnerable. Sorry for that @lenasokolova and thanks for being vigilant @wlechowicz ^^

2022-03-02 17:54 UTC, lenasokolova commented on app/components/Carousel/index.js
> +  // TODO: czy da się reagować tylko na zmianę rozmiaru samego CarouselOuter zamiast window?
I think it will stay like it for now. It does its job already, but it might do better.

2022-03-02 17:56 UTC, lenasokolova commented on app/components/Carousel/index.js
> +  // TODO: czy da się reagować tylko na zmianę rozmiaru samego CarouselOuter zamiast window?
I think it will stay like it for now. It does its job already, but it might do better.

2022-03-03 21:58 UTC, rast-mk1 requested changes
In Storybook preview, whole Carousel has `pointer: cursor`, not just the Movie Cards. That's something that may be misleading for the user.

2022-03-04 13:07 UTC, weronika299 reviewed
I think that it looks good now but what do you think about  change order of folders like that: Carousel/Carousel.stories.js not Carousel/CarouselStories/Carousel.stories.js and the same with NavButton so without additional NavButtonStories and CarouselStories folder?

2022-03-05 22:53 UTC, marcelina-hasiak requested changes

2022-03-05 22:53 UTC, marcelina-hasiak commented on app/components/Carousel/CarouselStories/importMovies.js
> +export default Movies;
You can name this file 'index.js' To repeat name structure just like you did for NavButton
<img width="215" alt="Zrzut ekranu 2022-03-5 o 23 05 01" src="https://user-images.githubusercontent.com/62512837/156901298-194c0ab3-6916-4732-9e5e-0e0d826d8a41.png">
'

2022-03-05 22:53 UTC, marcelina-hasiak commented on app/components/Carousel/index.js
> +      if (windowWidth > 768) {
768px is already tablet width so the conditional should looks like (windowWidth >= 768) same for Line:30 for laptop width (windowWidth >= 1024)

2022-03-06 12:14 UTC, lenasokolova commented
> In Storybook preview, whole Carousel has `pointer: cursor`, not just the Movie Cards. That's something that may be misleading for the user.

right, I moved it from CarosuelItemWrapper -> CarouselItemInner.

2022-03-06 21:38 UTC, rast-mk1 approved these changes

2022-03-07 02:53 UTC, wlechowicz requested changes
I'm not sure why you have a folder named "NavButtonStories". If it's where you want to have the NavButton, then name it NavButton. Carousel has its own NavButton however. Confusing.

2022-03-07 02:53 UTC, wlechowicz commented on app/components/Carousel/index.js
> +    );
First off, you need the listener function in a const because you need to reference it when removing the listener, like `const resizeListener = throttle(() => ... );` then add it with `window.addEventListener('resize', resizeListener);`.
Second issue, you need to remove the listener when doing a cleanup. A cleanup in useEffect is done by returning a function, so you need to `return () => window.removeEventListener('resize', resizeListener);`

2022-03-07 02:53 UTC, wlechowicz commented on app/components/Carousel/index.js
> +          transform: `translateX(-${activeScreen * 100}%)`,
Pass `activeScreen` as a prop to CarouselInner and use it in its CSS, instead of inline style.

2022-03-07 02:53 UTC, wlechowicz commented on app/components/Carousel/Carousel.styles.js
> +export const NavButton = styled.button`
You have two NavButtons, one in Carousel, one in strangely named NavButtonStories.

2022-03-07 02:53 UTC, wlechowicz commented on app/components/Carousel/NavButtonStories/NavButton.stories.js
> +import NavButton from '.';
This is not the same NavButton that the Carousel is using.

2022-03-07 02:53 UTC, wlechowicz commented on app/components/Carousel/importMovies.js
> +export default Movies;
Looks like this isn't used anywhere, as well as the mockData.

2022-03-07 02:53 UTC, wlechowicz commented on app/components/Carousel/Carousel.styles.js
> +  right: 12px;
This can't be correct.

2022-03-14 03:54 UTC, wlechowicz requested changes
95% there, just some cleanup to do and LGTM

2022-03-14 03:54 UTC, wlechowicz commented on app/components/Carousel/Carousel.stories.js
> +import React from 'react';
This is unnecessary.

2022-03-14 03:54 UTC, wlechowicz commented on app/components/Carousel/importMovies.js
> +export default Movies;
Still not used, can be deleted IMO.

2022-03-14 03:54 UTC, wlechowicz commented on app/components/Carousel/index.js
> +  };
Please move this outside of the Carousel component (in his file, before the Carousel function is defined).

2022-03-14 03:54 UTC, wlechowicz commented on app/components/Carousel/index.js
> +  numOfChildren: PropTypes.oneOf([2, 3, 6]),
This isn't a prop of this component, it's your helper prop in the story. You should remove this from here and add a `movies` PropType instead (Array).

2022-03-14 03:54 UTC, wlechowicz commented on lib/carousel/mockData.js
> +];
Not needed, you generate those in the story dynamically. Please remove.

2022-03-14 03:54 UTC, wlechowicz commented on app/components/Carousel/Carousel.stories.js
> +};
`viewport` is a parameter, but `numOfChildren` is an argument, so should be in `CarouselDesktop.args` not parameters. Applies to all the rest of the stories too.

2022-03-14 11:46 UTC, weronika299 approved these changes

2022-03-14 22:16 UTC, wlechowicz commented on app/components/Carousel/Carousel.stories.js
> +};
This still needs fixing.

2022-03-15 21:36 UTC, marcelina-hasiak approved these changes

2022-03-16 00:50 UTC, wlechowicz approved these changes

2022-03-16 16:04 UTC, wlechowicz commented
@hiimsagan your review with change requests is stale.

2022-03-16 18:26 UTC, wlechowicz commented
@lenasokolova let's get this merged!

2022-03-16 18:52 UTC, merged