Feature/SimpleHeader component
intive/patronage22_poznan_js pull request #26
Opened 2022-02-08 20:44 UTC by marcelina-hasiak

2022-02-09 12:08 UTC, wlechowicz requested changes

2022-02-09 12:08 UTC, wlechowicz commented on app/components/Header/simple-header.js
> +  @media only screen and (min-width: 768px) {
Please use this approach to define reusable media queries: https://jsramblings.com/how-to-use-media-queries-with-styled-components/
If we're going with mobile-first approach, then we only need 1 breakpoint: `tablet: 768px` so that base CSS is for mobile up to 768 and then inside media query it's for tablets and desktops 768 and up. (like you did here)

2022-02-09 12:08 UTC, wlechowicz commented on app/components/Header/simple-header.js
> +import LogoLink from "components/LogoLink/logo-link";
This is an unnecessary nesting in import path caused by misnaming of the module. Module should be named 'components/LogoLink/index.js' or 'components/LogoLink.js', in both cases the import becomes 'from "components/LogoLink"'.
Same applies to this Header component.

2022-02-09 12:08 UTC, wlechowicz commented on app/components/Header/simple-header.js
> +import { PrimaryButton } from "../Button/button";
1. Button button, ditto
2. Import path should be "components/Button"

2022-02-09 16:51 UTC, marcelina-hasiak commented
Attention: I'm currently waiting for this PR: https://github.com/intive/patronage22_poznan_js/pull/29 to be resolved before this one.

2022-02-09 17:17 UTC, marcelina-hasiak commented on app/components/Header/simple-header.js
> +  @media only screen and (min-width: 768px) {
Thank you for this neat pattern ;)

2022-02-10 21:14 UTC, wlechowicz requested changes

2022-02-10 21:14 UTC, wlechowicz commented on app/components/SimpleHeader/index.js
> +import PrimaryButton from "../PrimaryButton/index";
Import path for components should be `components/` and you don't need to add `index` at the end, so: `from "components/PrimaryButton";`
I assume the double quotes are here because you didn't apply Prettier to this PR yet.

2022-02-10 21:15 UTC, wlechowicz commented
> For me it looks good.
@weronika299 then you should add your review and choose "Approve".

2022-02-10 21:33 UTC, weronika299 approved these changes

2022-02-11 21:45 UTC, marcelina-hasiak commented
<img width="745" alt="Zrzut ekranu 2022-02-11 o 22 30 49" src="https://user-images.githubusercontent.com/62512837/153674591-eb29dca0-4dbf-4b9c-bf4e-06d142698127.png">

2022-02-13 23:32 UTC, wlechowicz approved these changes

2022-02-13 23:33 UTC, wlechowicz commented
LGTM

2022-02-14 00:01 UTC, merged