feature/p2022 618 account page
intive/patronage22_poznan_js pull request #38
Opened 2022-02-14 16:21 UTC by marcelina-hasiak

2022-02-16 14:56 UTC, hiimsagan requested changes

2022-02-16 17:37 UTC, marcelina-hasiak commented on app/components/AppLogo/app-logo.js
> +  display: flex;
I doubled check and it simply does nothing (perhaps it's some leftovers after styling). Good point! I'll remove it. Thanks.

2022-02-16 18:16 UTC, marcelina-hasiak commented on app/utils/validate-form-inputs.js
> +const passwordPattern = /^(?=.*[A-Za-z])(?=.*\d)(?=.*[@$!%*#?&])[A-Za-z\d@$!%*#?&]{8,20}$/;
Ok. I fixed that. The problem wasn't partially in regex but the logic after form submitting - I didn't clear errorMsg state, so even if form was valid errorMsg still remained. After some digging it occurred regex has a bug and password didn't have to have an uppercase to be valid :D .

2022-02-16 21:45 UTC, weronika299 requested changes

2022-02-16 21:45 UTC, weronika299 commented on app/components/Form/email-veryfication-form.js
> +const EmailVeryficationForm = ({ onEmailVeryfication }) => {
typo

2022-02-16 21:45 UTC, weronika299 commented on pages/user/create-account.js
> +`;
Maybe it's better to move the styles to a separate file?

2022-02-16 21:45 UTC, weronika299 commented on pages/user/create-account.js
> +      style={{ minHeight: '100vh', backgroundColor: `${isUserPreVetted ? '#fff' : '#000'}` }}
Could you replace that as a styled component?

2022-02-18 12:22 UTC, wlechowicz requested changes
Bulk of changes requested over a call, too many little details to put in the PR comments and not make it a mess.

2022-02-20 22:08 UTC, wlechowicz requested changes
Bad file names:

- app/components/AppLogo/app-logo.js -> app/components/AppLogo/index.js
- app/components/Button/Button.js -> app/components/Button/index.js
- app/components/Form/input.js -> app/components/Form/Input.js
- app/components/Pages/CreateAccount/UserPrevet/UserPrevetForm.js -> app/components/Pages/CreateAccount/UserPrevetForm/index.js
- app/components/Pages/CreateAccount/UserSignUp/UserSignUpForm.js -> app/components/Pages/CreateAccount/UserSignUpForm/index.js

2022-02-20 22:08 UTC, wlechowicz commented on styles/globals.css
> +
That's a big global change, why do you need this?

2022-02-20 22:08 UTC, wlechowicz commented on app/components/Form/input.js
> +const InputWrapper = styled.div`
All of these till EOF should be in Input.styles.js
If this is a special case of a non-reusable input, then it should live with the CreateAccount page, not in the common Form component directory.

2022-02-21 18:05 UTC, MS151994 approved these changes

2022-02-22 02:02 UTC, marcelina-hasiak commented on styles/globals.css
> +
For these selectors - unnecessary margin top and bottom. For styling it would be clearer to set only one vertical margin.

2022-02-22 13:49 UTC, weronika299 requested changes

2022-02-22 13:49 UTC, weronika299 commented on app/components/Pages/CreateAccount/CreateAccount.styles.js
> +import BackgroundImage from '../../../../public/images/background-movies.jpeg';
This background image is already on develop because I added it  with LoginPage component.

2022-02-23 20:33 UTC, weronika299 commented on app/components/Pages/CreateAccount/CreateAccount.styles.js
> +  min-height: 85vh;
What do you think about min-height: 100vh in this place?:)

2022-02-23 23:01 UTC, marcelina-hasiak commented on app/components/Pages/CreateAccount/CreateAccount.styles.js
> +  min-height: 85vh;
If I added 100vh I would lost black area at the bottom. I leave it as it is now because the design'll be changed anyway ;)

2022-02-23 23:09 UTC, weronika299 approved these changes

2022-02-23 23:41 UTC, wlechowicz requested changes
- AppLogo file name still wrong
- validate util file name wrong
- Please create a UI folder inside components and move Spinner there. That Miscelelescenious folder name is longer than my career.

2022-02-23 23:41 UTC, wlechowicz commented on app/components/Button/Button.styles.js
> +      @media (min-width: 768px) {
Should have used the shared media queries.

2022-02-24 23:48 UTC, wlechowicz approved these changes

2022-02-24 23:50 UTC, wlechowicz commented
@hiimsagan you forgot to approve since all your requested changes were made.

2022-02-25 21:07 UTC, hiimsagan approved these changes
LG 👍

2022-02-25 21:09 UTC, merged