feat: feature/p2022 674 search component and funcionality
intive/patronage22_poznan_js pull request #45
Opened 2022-02-18 13:42 UTC by MS151994

2022-02-20 22:36 UTC, wlechowicz requested changes
Please rename 
- app/components/SearchMoviesInput/SearchMoviesInput.js -> app/components/SearchMoviesInput/index.js
- app/components/SearchMoviesInput/searchMovieInputStyles.js -> app/components/SearchMoviesInput/SearchMoviesInput.styles.js

2022-02-20 22:36 UTC, wlechowicz commented on app/components/SearchMoviesInput/SearchMoviesInput.js
> +  const containerBackground = isExpanded ? 'rgba(0, 0, 0, 0.8)' : 'none';
These styles shouldn't be defined here. You can pass the isExpanded prop and use in the CSS to change the styles by defining the collapsed state as default, then like this
```
width: 30px;
background...

${({ isExpanded }) => isExpanded && css(`
  width: 300px;
  background...
`)}

2022-02-21 12:27 UTC, wlechowicz requested changes

2022-02-21 22:10 UTC, wlechowicz requested changes

2022-02-21 22:10 UTC, wlechowicz commented on app/components/SearchMoviesInput/SearchMoviesInput.styles.js
> +import { device } from '/app/consts/mediaQueries';
```suggestion
import { device } from 'consts/mediaQueries';
```

2022-02-21 23:00 UTC, MS151994 commented on app/components/SearchMoviesInput/index.js
> +      {searchInputValue.length > 0 && (
like this? 
`const [isInputEmpty, setInputEmpty] = useState(true);
 
  const changeInputValue = (e) => {
    const value = e.target.value;
    setSearchInputValue(value);
    value.length === 0 ? setInputEmpty(true) : setInputEmpty(false);
  };`
  
  onChange={(e) => changeInputValue(e)}

2022-02-22 22:45 UTC, rast-mk1 commented
Is Search Component supposed to be invisible on mobile? 

![obraz](https://user-images.githubusercontent.com/56893415/155232179-24e3965c-3b16-4615-91bb-6bc2432654bd.png)

2022-02-23 19:40 UTC, MS151994 commented
> Is Search Component supposed to be also in mobile?
> 
> ![obraz](https://user-images.githubusercontent.com/56893415/155232179-24e3965c-3b16-4615-91bb-6bc2432654bd.png)

i don't know. i suggested original netflix site on web browser, there is no search there component on mobile.

2022-02-23 23:45 UTC, wlechowicz commented on app/components/SearchMoviesInput/index.js
> +      {searchInputValue.length > 0 && (
No, just `const isInputEmpty = searchInputValue.length > 0;`

2022-02-24 19:10 UTC, marcelina-hasiak requested changes

2022-02-24 19:10 UTC, marcelina-hasiak commented on app/components/SearchMoviesInput/index.js
> +  };
I can have some value inside input and can't close it when I click outside, but I can close it when I click SearchButton - missing logic for checking if input is empty

2022-02-26 17:40 UTC, rast-mk1 commented
What do you think about writing story or stories for `SearchMoviesInput` so there's Storybook preview?

2022-02-26 21:02 UTC, hiimsagan commented on app/components/SearchMoviesInput/SearchMoviesInput.styles.js
> +
Are you sure you wanna expand button? Mabye Some div ?

2022-02-28 00:48 UTC, marcelina-hasiak requested changes
Too much to talk about here, I'll leave a piece of advice advices in DM

2022-02-28 00:48 UTC, marcelina-hasiak commented on app/components/SearchMoviesInput/SearchMoviesInput.styles.js
> +
This component is unnecessary.

2022-03-11 19:27 UTC, closed without merging