Feature/p2022 362 sign up
intive/patronage22_poznan_js pull request #5
Opened 2022-01-25 17:34 UTC by marcelina-hasiak

2022-01-25 18:52 UTC, wlechowicz requested changes
I'm worried that changing the shared `input` might have broken login. Pls check.

2022-01-25 18:52 UTC, wlechowicz commented on app/components/Form/form-styling-components.js
> +`;
Used semantic article, nice!

2022-01-25 18:52 UTC, wlechowicz commented on app/components/Form/index.js
> +                <FormInput
You changed the common component input, risky, does login still work?

2022-01-26 15:12 UTC, marcelina-hasiak commented on pages/user/login.js
> +`;
Yeah! I thought about it, but then I went soft because of so many changes at `login.js` and `index.js`. But if you noticed it, I'll definitely fix it ;) Thanks!

2022-01-26 18:50 UTC, marcelina-hasiak commented on app/components/Form/index.js
> +                <FormInput
I've adapted `login.js` to `Input` component changes and double checked. Everything's under control ;)

2022-01-27 13:16 UTC, weronika299 commented on pages/user/sign-up.js
> +            }
I'm not sure if this is necessary. You set these values ​​to empty string also at the beginning.

2022-02-07 11:26 UTC, danielmajewski commented on app/utils/validateFormInputs.js
> +export const validateFormInputs = (inputValues) => {
this is validating specific form. Maybe rename to `validateSignUpFormInputs`

2022-02-07 11:26 UTC, danielmajewski commented on app/utils/validateFormInputs.js
> +    }
You could extract these validators into seperate functions so someone can reuse then in different forms

e.g.:
```suggestion
const emailValidator = (value) => {
    if (!value) {    
        return 'Email jest wymagany'
    } else if (!emailPattern.test(email)) {
        return 'Wprowadź prawidłowy adres email'
    }
    
    return '';
}
```

So each validator returns an error or empty string (if there is no error);

2022-02-07 11:26 UTC, danielmajewski commented on app/components/Form/form-styling-components.js
> +export { FormWrapper, FormContent, Form, FormTitle, FormButton, FormRow, FormLabel, FormInput, ErrorMsg, Wrapper, FormFlex }
why export like that? why not `export const FormFlex = styled.form...`

2022-02-07 11:26 UTC, danielmajewski commented on pages/user/sign-up.js
> +            }
So if form is valid (no errors) then you're clearing the form? Why?
I think you could add function that will contain all form data that would need to be send to API? Maybe `handleFormData`

2022-02-09 16:28 UTC, closed without merging