feat: add icon component #1221
intive/patronage22_poznan_js pull request #50
Opened 2022-02-21 00:04 UTC by rast-mk1

This one adds Icon component and it's story in Storybook with some of Font Awesome features. It's in draft since I need insight on how to write proper tests for it.

2022-02-22 10:27 UTC, weronika299 commented on app/components/Icon/Icon.stories.js
> +};
I don't fully understand what is characteristic of pulse and spin now. Will styles be added to them as well?

2022-02-22 10:36 UTC, rast-mk1 commented on app/components/Icon/Icon.stories.js
> +};
Both are optional, simple FontAwesome built in features. Spin makes Icon rotate in a smooth manner, while pulse makes it rotate in a more rough way. Custom css can be used instead.

2022-02-22 11:04 UTC, weronika299 commented on app/components/Icon/Icon.stories.js
> +};
Ok, I get it. :)

2022-02-22 11:06 UTC, weronika299 approved these changes

2022-02-22 22:16 UTC, MS151994 approved these changes
looks good to me

2022-02-23 23:55 UTC, wlechowicz approved these changes

2022-02-24 00:58 UTC, marcelina-hasiak requested changes

2022-02-24 00:58 UTC, marcelina-hasiak commented on app/components/Icon/Icon.stories.js
> +  backgroundColor: 'white',
#159 #166 Just quick request for simple change: could you please set background-color to color, which won't be white? Icon animation is invisible in Storybook now
<img width="400" alt="Zrzut ekranu 2022-02-24 o 01 56 51" src="https://user-images.githubusercontent.com/62512837/155436578-33121c11-3e74-4928-88a2-e2d52139ffd9.png">

2022-02-24 10:09 UTC, rast-mk1 commented on app/components/Icon/Icon.stories.js
> +  backgroundColor: 'white',
That's weird, I have no problems like that neither on my localhost nor on PR's storybook preview

2022-02-24 10:24 UTC, rast-mk1 commented on app/components/Icon/Icon.stories.js
> +  backgroundColor: 'white',
![obraz](https://user-images.githubusercontent.com/56893415/155506093-d7261527-dde0-4233-93f1-410d6af0874c.png)

2022-02-24 18:38 UTC, marcelina-hasiak approved these changes

2022-02-24 23:48 UTC, wlechowicz commented
@rast-mk1 check the changes to Icon in Chromatic, if the padding change is intended then approve, if it's not then fix. After everything is approved in Chromatic, you can merge.

2022-02-25 23:51 UTC, merged