refactor/add storybook
intive/patronage22_poznan_js pull request #51
Opened 2022-02-22 21:17 UTC by wolnio

2022-02-24 00:26 UTC, marcelina-hasiak requested changes

2022-02-24 00:26 UTC, marcelina-hasiak commented on app/components/MovieHero/MovieHero.styles.js
> +  flex-direction: row;
`flex-direction: row` is default when you declare flex, you can remove this line.

2022-02-24 00:26 UTC, marcelina-hasiak commented on app/components/MovieHero/MovieHero.stories.js
> +  ],
The reason why background image  and title can't load inside our storybook is that you pass movie details object inside array.

2022-02-27 10:39 UTC, wolnio commented on app/components/MovieHero/MuteIcon.js
> +    <Button type="button" onClick={props.onClick} aria-pressed="false">
Oh, you're right, it's a testing residue. Aria was necessary to work with `play` function in StoryBook.

2022-02-27 11:10 UTC, wolnio commented on app/components/MovieHero/MediaButton.js
> +export function MediaButton(props) {
Well, when I add `default` I get a following error: `Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.`

2022-02-28 01:16 UTC, marcelina-hasiak approved these changes
1. Do you happen to know why this file is part of your PR?
<img width="400" alt="Zrzut ekranu 2022-02-28 o 02 07 07" src="https://user-images.githubusercontent.com/62512837/155908698-d56a0001-5003-4171-ac30-8cb4d7c5a1b0.png">
2. I assume you set this file in different PR? It needs to be changed to 'movie-hero'
<img width="166" alt="Zrzut ekranu 2022-02-28 o 02 09 26" src="https://user-images.githubusercontent.com/62512837/155908770-c09f8dbb-2d20-425c-8167-73a51f7755c8.png">  You can create a bug task in Jira and resolve it later on new branch.

Please investigate point 1. and change the export, apart from that everything looks good now ;)

2022-02-28 01:16 UTC, marcelina-hasiak commented on app/components/MovieHero/MediaButton.js
> +export function MediaButton(props) {
Please remember to change import as well: `import MediaButton` not `import {MediaButton}`

2022-03-16 16:34 UTC, closed without merging