Sign up and validate form
intive/patronage22_poznan_js pull request #6
Opened 2022-01-25 18:19 UTC by hiimsagan

2022-01-25 19:06 UTC, wlechowicz requested changes

2022-01-25 19:06 UTC, wlechowicz commented on pages/user/register.js
> +        label="username"
Dulplication

2022-01-26 11:33 UTC, lenasokolova commented on pages/user/register.js
> +  }
there are some typos in here, pls check

2022-01-26 11:33 UTC, lenasokolova commented on pages/user/register.js
> +    let size = (Object.keys(validateErrors).length)
I believe it's not the best way to name the variable, maybe smth more related to the validateErrors object's name.

2022-01-26 16:50 UTC, rast-mk1 commented on pages/user/register.js
> +    }
could use RegExp;

checking email format and email / confirmEmail values could be (doesn't have to) inside if () for email length

2022-01-26 20:33 UTC, marcelina-hasiak commented on pages/user/register.js
> +    }
Adding type='email' to your html input provide you html validation (unless you didn't turn it off in your script) and '@' is necessary to pass this validation. I assume `allValues.confirmEmail.length > 0` is equal jus to `allValues.confirmEmail`.

2022-01-26 20:35 UTC, marcelina-hasiak reviewed
Nicely done!

2022-01-26 21:54 UTC, marcelina-hasiak commented on pages/user/register.js
> +    console.log(newUser)
Line:69 Empty newUser object appears in console even after submitting an empty form (for the first time). Please check this out ;)

2022-01-27 12:34 UTC, weronika299 commented on pages/user/register.js
> +    }
If the user does not fill in the field confirm email, would it be better to use a different message?

2022-02-03 17:57 UTC, closed without merging