feat: redesign authentication page container
intive/patronage22_poznan_js pull request #60
Opened 2022-03-03 17:16 UTC by weronika299

2022-03-06 01:10 UTC, marcelina-hasiak requested changes

2022-03-06 01:10 UTC, marcelina-hasiak commented on app/components/Pages/AuthenticationPageContainer/index.js
> +  const isSignInPage = pageLayout.signIn !== false;
In this situation we pass boolean values inside getServerSideProps() so simply `const isSignInPage = pageLayout.signIn` is all we need here.  Component can be extended with Prop types to secure ourselves that we expect boolean values

2022-03-06 01:10 UTC, marcelina-hasiak commented on app/components/Form/AuthenticationFormHeader/index.js
> +        <a href="create-account">Sign up</a>
use `<Link>` in such situations

2022-03-06 01:10 UTC, marcelina-hasiak commented on app/components/Form/AuthenticationFormHeader/index.js
> +      {isSignInPage ? <Underlined /> : <Underlined style={{ marginLeft: '102px' }} />}
I don't think we need separate component just to underline active form, you can do it with props and css only

2022-03-06 12:17 UTC, marcelina-hasiak commented on app/components/Form/AuthenticationFormHeader/index.js
> +      <h1>inTiVi</h1>
Logo is ready to be applied here.

2022-03-06 13:48 UTC, marcelina-hasiak commented on app/components/Pages/AuthenticationPageContainer/AuthenticationPageContainer.styles.js
> +    background-image: url('../images/background-image.jpg');
What do you think about giving our background image more semantic name? It could be more background images in the future, so marking this particular image as hero one would be a good move.

2022-03-06 14:14 UTC, weronika299 commented on pages/user/sign-in.js
> +}
Ok, right. I will fix it and I will make only one page.

2022-03-06 18:31 UTC, lenasokolova commented on app/components/Pages/AuthenticationPageContainer/AuthenticationPageContainer.stories.js
> +
don't you think you could use here `defaultViewport: 'responsive'`
?
like this:

```suggestion
export const DesktopView = Template.bind({});
DesktopView.parameters = {
  viewport: {
    defaultViewport: 'responsive',
  },
};
```

2022-03-07 02:55 UTC, wlechowicz commented on app/components/Form/AuthenticationFormHeader/index.js
> +        <a href="create-account">Sign up</a>
And an absolute path like "/sign-in" and "/sign-up".

2022-03-07 02:56 UTC, wlechowicz commented on app/components/Form/AuthenticationFormHeader/index.js
> +      {isSignInPage ? <Underlined /> : <Underlined style={{ marginLeft: '102px' }} />}
A prop like `active` true/false that's true on active tab and the tab styles itself.

2022-03-08 12:34 UTC, wlechowicz approved these changes
Looks good, one change requested but overall approved.

2022-03-08 12:34 UTC, wlechowicz commented on app/components/Pages/AuthenticationPageContainer/index.js
> +  const [activeMode] = useState({ active });
Seems to me like you don't need to store this `active` prop in state since you're not modifying it. You can just use the prop directly in render.

2022-03-08 13:45 UTC, weronika299 commented on app/components/Pages/AuthenticationPageContainer/index.js
> +  const [activeMode] = useState({ active });
Ok, I have already changed it. :)

2022-03-08 22:14 UTC, marcelina-hasiak approved these changes

2022-03-09 21:10 UTC, merged