feat: add MetaData component
intive/patronage22_poznan_js pull request #62
Opened 2022-03-05 23:33 UTC by wolnio

2022-03-06 13:35 UTC, marcelina-hasiak requested changes

2022-03-06 13:35 UTC, marcelina-hasiak commented on app/components/MovieHero/MetaData/index.js
> +  };
You could use `movieMockData.json` file and just import it.

2022-03-06 13:35 UTC, marcelina-hasiak commented on app/components/MovieHero/MetaData/MetaData.styles.js
> +  margin: ${({ margin }) => margin || '0 0 0 0'};
I would use only margin-bottom here (spacing between title and MetaData you'll achieve by adding margin-bottom to title), but if you like to keep margin-top as well - no problem. However, horizontal margin are unnecessary.

2022-03-06 13:35 UTC, marcelina-hasiak commented on app/components/MovieHero/MetaData/MetaData.styles.js
> +`;
Simply padding-right is all you need here. Try: 
```
&:not(:last-child) {
  padding-right: 16px
}
```

2022-03-06 14:04 UTC, marcelina-hasiak commented on app/components/MovieHero/MetaData/MetaData.styles.js
> +const MetaDataItem = styled.span`
Span hasn't got semantic meaning. It's good to use it as separator but use paragraph to wrap important data.

2022-03-07 02:05 UTC, wlechowicz commented on app/components/MovieHero/MetaData/index.js
> +  };
This file needs to go away, actually I should have deleted it when I added first 2 movies endpoints.

2022-03-07 02:07 UTC, wlechowicz commented on app/components/MovieHero/MetaData/MetaData.styles.js
> +  margin: ${({ margin }) => margin || '0 0 0 0'};
The outer-most component shouldn't have any margins at all. If anything, it should use padding for internal spacing. This will make composing this component with others easier.

2022-03-07 02:25 UTC, wlechowicz requested changes
Like I said in standup, this component should not be located inside MovieHero, because it will be used in multiple locations. Please move it to components/UI.

2022-03-07 02:25 UTC, wlechowicz commented on app/components/MovieHero/MetaData/index.js
> +  };
Please don't use mock data in the component itself. You can use it in the story to showcase how the component works.

2022-03-07 02:25 UTC, wlechowicz commented on app/components/MovieHero/MetaData/index.js
> +    <MetaDataWrapper {...props}>
You're passing entire `props` object to child, this means that most likely something's wrong with composition or logic placement - as a general rule. The wrapper only uses `margin` prop, so only that prop should be passed.

2022-03-07 02:25 UTC, wlechowicz commented on app/components/MovieHero/MetaData/index.js
> +    </MetaDataWrapper>
That's a lot of `MetaData` in the names, I think you should drop this and just name them `Separator`, `Wrapper`, `Item`. They are local to your component so the generic naming is fine.

2022-03-07 02:25 UTC, wlechowicz commented on app/components/MovieHero/MetaData/MetaData.stories.js
> +import MetaData from './';
I suggest renaming the whole component to `MovieMetadata`.

2022-03-07 02:25 UTC, wlechowicz commented on app/components/MovieHero/MetaData/MetaData.styles.js
> +  font-size: 14px;
Font size should be either relative to its surroundings (`em`), or constant but with `rem`.

2022-03-07 02:25 UTC, wlechowicz commented on app/components/MovieHero/MetaData/MetaData.styles.js
> +const MetaDataItem = styled.span`
`p` would be a bit annoying to style and wouldn't be very fitting semantic-wise. The best solution for this whole component would be to use a list `ul` and make it inline.

2022-03-09 23:17 UTC, wolnio commented on app/components/MovieHero/MetaData/MetaData.styles.js
> +  font-size: 14px;
Should I stick to the design and do some unit conversion, so `font-size` with `em/rem` would have similar size in `px`?

2022-03-10 11:41 UTC, wolnio commented on app/components/MovieHero/MetaData/MetaData.styles.js
> +`;
Well, I need some space on both sides of my 'bullet-like' separator. This code will give me space only on the right side.

2022-03-10 20:13 UTC, marcelina-hasiak commented on app/components/MovieHero/MetaData/MetaData.styles.js
> +  font-size: 14px;
Exactly. Remember round this values if needed, we're not pixel perfect here ;)

2022-03-10 20:13 UTC, marcelina-hasiak commented on app/components/MovieHero/MetaData/MetaData.styles.js
> +  font-size: 14px;
Exactly. Remember round this values if needed, we're not pixel perfect here ;)

2022-03-11 11:21 UTC, weronika299 requested changes

2022-03-11 11:21 UTC, weronika299 commented on app/components/UI/MovieMetadata/MovieMetadata.stories.js
> +  marginBottom: '0',
You should use it in MovieMetadata.styles.js

2022-03-11 11:21 UTC, weronika299 commented on app/components/UI/MovieMetadata/index.js
> +import PropTypes from 'prop-types';
You declared it but you didn't use it.

2022-03-11 19:27 UTC, wlechowicz requested changes
This PR is for MovieMetadata component only, MovieHero component should not be a part of it.

2022-03-11 19:27 UTC, wlechowicz commented on app/components/MovieHero/MovieHero.stories.js
> +import React from 'react';
Not needed.

2022-03-11 19:27 UTC, wlechowicz commented on app/components/UI/MovieMetadata/MovieMetadata.styles.js
> +  color: #fff;
`color` should be inherited from parent, this way this component will work anywhere it's used.

2022-03-11 19:27 UTC, wlechowicz commented on app/components/UI/MovieMetadata/MovieMetadata.styles.js
> +  top: 50%;
This should have no effect since it's inline.

2022-03-11 19:27 UTC, wlechowicz commented on app/components/UI/MovieMetadata/index.js
> +export default function MovieMetadata({ ...props }) {
`({ ...props })` does nothing, it's the same as `(props)`. You should destructure the props that you need with `({ release_date, vote_average, popularity })`

2022-03-11 19:47 UTC, wolnio commented on app/components/UI/MovieMetadata/MovieMetadata.stories.js
> +  marginBottom: '0',
Thats right, forgot to remove it after latest review

2022-03-14 19:56 UTC, rast-mk1 commented on app/components/UI/MovieMetadata/MovieMetadata.styles.js
> +  transform: translateY(-50%);
Why do you need transform?

2022-03-14 20:34 UTC, weronika299 approved these changes
Looks good to me.

2022-03-14 21:30 UTC, wlechowicz requested changes

2022-03-14 21:30 UTC, wlechowicz commented on app/components/UI/MovieMetadata/index.js
> +export default function MovieMetadata({ release_date, vote_average, popularity }) {
The data should come in as a single prop like `movieData` and then be further destructured into those fields. When destructuring, please change snake_case to camelCase.

2022-03-14 23:23 UTC, marcelina-hasiak approved these changes

2022-03-14 23:23 UTC, marcelina-hasiak commented on app/components/UI/MovieMetadata/MovieMetadata.styles.js
> +  transform: translateY(-50%);
it's same as `vertical-align: middle` - center the bullet

2022-03-15 15:01 UTC, wolnio commented on app/components/UI/MovieMetadata/index.js
> +export default function MovieMetadata({ release_date, vote_average, popularity }) {
Ok, I wanted to keep variable names as they are in JSON response from movie API, but will change it :)

2022-03-16 00:39 UTC, wlechowicz commented on app/components/UI/MovieMetadata/index.js
> +export default function MovieMetadata({ release_date, vote_average, popularity }) {
Yeah it really is something that should be done on the backend. @rast-mk1 can you add the snake case to camel case transform to movieDb client? Like this https://stackoverflow.com/a/61375162

2022-03-16 00:39 UTC, wlechowicz approved these changes

2022-03-16 06:18 UTC, merged