feat: redesign input components
intive/patronage22_poznan_js pull request #63
Opened 2022-03-07 13:04 UTC by weronika299

2022-03-07 18:27 UTC, marcelina-hasiak requested changes

2022-03-07 18:27 UTC, marcelina-hasiak commented on app/components/Form/Input/Input.styles.js
> +  font-size: 14px;
It's been already said in different PR to use em or rem units for font-size

2022-03-08 22:29 UTC, marcelina-hasiak commented on app/components/Form/Input/index.js
> +      {label && <InputLabel htmlFor={id}>{label}</InputLabel>}
As far as I know input always should has a label even if it's hidden. I would remove this conditional rendering - I didn't catch this previously and sorry for that ^^'

2022-03-09 10:23 UTC, weronika299 commented on app/components/Form/Input/Input.styles.js
> +  }
I need this to show the label when I have text in the input. 
![password input](https://user-images.githubusercontent.com/97474985/157421785-6a05d51c-a194-4eef-8132-3f0e010d5678.PNG)
![figma input](https://user-images.githubusercontent.com/97474985/157422495-1b3bf729-e932-4571-ae49-8c5a1820bed4.PNG)

2022-03-09 20:18 UTC, marcelina-hasiak commented on app/components/Form/Input/Input.styles.js
> +  }
Ok, I know what you mean but you have something like this:   

```
input:focus + ${InputLabel} {
    display: none;
 }
```
 1. I would remove hiding label on focus input entirely and animate this floating label by adding some transition
 2. Input value and label need more placement adjusting:
<img width="280" alt="Zrzut ekranu 2022-03-9 o 20 22 21" src="https://user-images.githubusercontent.com/62512837/157525421-25d68c4b-ea21-4460-a0cf-ce1db5c64c3a.png">
<img width="322" alt="Zrzut ekranu 2022-03-9 o 20 23 41" src="https://user-images.githubusercontent.com/62512837/157525432-f2375c73-1721-46d4-9133-0db00c0ee15b.png">
3. About storybook... Label doesn't float because input state isn't update and the value equals "" all the time. I tried to pass some function inside inInputChange arg but it didn't help. I don't how to solve it and if solution is needed at all ??

2022-03-09 22:53 UTC, marcelina-hasiak requested changes
Input component with its own state in story works good now. Don't know other/better solution how to present label changing state. To be continued on daily or with @wlechowicz earlier here.

2022-03-09 22:53 UTC, marcelina-hasiak commented on app/components/Form/Input/Input.stories.js
> +      }}
Don't need to call args.onInputChange(e.target.value) here in story, onChange={(e) => setValue(e.target.value)} will be enough for our purpose.

2022-03-09 22:53 UTC, marcelina-hasiak commented on app/components/Form/Input/Input.stories.js
> +  const [value, setValue] = useState(args.value ?? '');
const [value, setValue] = useState(args.value || '')

2022-03-10 09:56 UTC, weronika299 commented on app/components/Form/Input/Input.stories.js
> +  const [value, setValue] = useState(args.value ?? '');
Why not double question mark? I set value on args.value but if it is null or undefined I set ''.

2022-03-10 10:29 UTC, marcelina-hasiak approved these changes

2022-03-10 10:29 UTC, marcelina-hasiak commented on app/components/Form/Input/Input.stories.js
> +  const [value, setValue] = useState(args.value ?? '');
Hmmmm... I compared it with || and didn't see any differences. Could you explain it to me in DM? I’m surely missing the point.

2022-03-11 10:42 UTC, hiimsagan approved these changes
Looks Good

2022-03-11 18:55 UTC, wlechowicz approved these changes

2022-03-12 12:41 UTC, merged