feat: add MovieCard Component #1405
intive/patronage22_poznan_js pull request #64
Opened 2022-03-07 23:03 UTC by rast-mk1

2022-03-07 23:09 UTC, rast-mk1 commented on app/components/UI/MovieCard/MovieCard.stories.js
> +};
Guys, Storybook won't render MovieCard. I guess it's because of fetching done in `MovieCard/index.js`. Need some suggestions.

2022-03-07 23:15 UTC, rast-mk1 commented on app/components/UI/MoviePoster/MoviePoster.styles.js
> +const StyledMoviePoster = styled.img`
Went for `img` instead of `Image` Component after all.

2022-03-08 12:43 UTC, wlechowicz requested changes

2022-03-08 12:43 UTC, wlechowicz commented on app/components/UI/MovieCard/index.js
> +  }, [id, setPoster]);
This should not be here at all. Parent component will provide img URL to movie card.

2022-03-08 12:43 UTC, wlechowicz commented on app/components/UI/MoviePoster/index.js
> +  ]),
Nope, can't be like that in the component. If you want to use some example, do it in stories.

2022-03-08 12:43 UTC, wlechowicz commented on app/components/UI/MoviePoster/index.js
> +}
You're not doing anything here so you have an unnecessary wrapper, so you can just export StyledMoviePoster.

2022-03-09 22:50 UTC, rast-mk1 commented on app/components/UI/MovieCard/index.js
> +  }, [id, setPoster]);
Got rid of it.

2022-03-09 22:50 UTC, rast-mk1 commented on app/components/UI/MoviePoster/index.js
> +  ]),
Moved these to stories.

2022-03-09 22:51 UTC, rast-mk1 commented on app/components/UI/MoviePoster/index.js
> +}
Got rid of styling for MoviePoster.

2022-03-09 23:00 UTC, rast-mk1 commented
Since MovieCard will populate Carousel, please take a look @lenasokolova

2022-03-11 12:03 UTC, hiimsagan reviewed
LG GJ

2022-03-11 12:17 UTC, rast-mk1 commented on next.config.js
> +  },
You need this, so Image component will let you render images from this domain.

2022-03-11 12:17 UTC, rast-mk1 commented on app/components/UI/MovieCard/MovieCard.styles.js
> +export const Wrapper = styled.div`
OK, seems reasonable, thanks.

2022-03-11 13:19 UTC, weronika299 commented on app/components/UI/MovieCard/index.js
> +    <>
Do you need it?

2022-03-11 13:27 UTC, rast-mk1 commented on app/components/UI/MovieCard/index.js
> +    <>
Well, either MovieCard or some inner container of Carousel is gonna have a way of handling user's click, so I guess it could be here for now.

2022-03-11 13:27 UTC, rast-mk1 commented on app/components/UI/MovieCard/index.js
> +        <a>
@wlechowicz suggested Link, so this is what I did.

2022-03-11 13:38 UTC, weronika299 commented on app/components/UI/MovieCard/index.js
> +        <a>
Yes, but if you use Link component, do you need 'a' tag also?

2022-03-11 13:42 UTC, weronika299 commented on app/components/UI/MovieCard/index.js
> +    <>
I think about this empty tag. Do you need this as an additional wrapper? You have Link component and this component is also your container.

2022-03-11 13:44 UTC, rast-mk1 commented on app/components/UI/MovieCard/index.js
> +        <a>
According to next/link documentation, `<a>` is optional, so I guess it's not needed. But again, this will be reworked, so I didn't really give it much thought at the moment.

2022-03-11 13:48 UTC, rast-mk1 commented on app/components/UI/MovieCard/index.js
> +        <a>
Yeah, forgot about this bit. Thanks

2022-03-11 13:50 UTC, rast-mk1 commented on app/components/UI/MovieCard/index.js
> +    <>
Yeah, forgot about this bit. Thanks.

2022-03-11 19:11 UTC, wlechowicz approved these changes
Overall approved, but some minor comments from other reviews still to be addressed.

2022-03-11 19:28 UTC, hiimsagan approved these changes

2022-03-12 14:36 UTC, merged