fix: form display on mobile devices
intive/patronage22_poznan_js pull request #67
Opened 2022-03-13 13:06 UTC by weronika299

2022-03-13 19:13 UTC, marcelina-hasiak requested changes
<img width="1419" alt="Zrzut ekranu 2022-03-13 o 19 56 05" src="https://user-images.githubusercontent.com/62512837/158074838-014220f7-55bb-416f-bfef-8dbafe0e9b17.png">
I know this fix is related to mobile only, but can we fix desktop view as well? After adding form component I met some issues: 
1. Missing padding top and bottom
2. Way to big logo, I tested some values and `width: clamp(70px,10vw,100px)` added for StyledLogoLink component fits good even for header
3. Missing spacing below Sign-up and Sign-in tabs
* I think input appearance where all 3 inputs display error message is too much. Try to set green border 1px width and error messages to font-size: 500 or 400 and check the outcome

2022-03-13 21:17 UTC, wlechowicz commented
Definitely the rectangle container should have an all-around padding to give some breathing room for its contents.
Also the logo shouldn't be clickable, there's no point in redirecting to home page from this screen.

2022-03-14 16:46 UTC, wlechowicz approved these changes

2022-03-14 22:18 UTC, marcelina-hasiak approved these changes

2022-03-14 22:48 UTC, merged