feat: sign-in component
intive/patronage22_poznan_js pull request #72
Opened 2022-03-14 19:35 UTC by weronika299

Mobile view is fixed in a separate PR that fixed AuthenticationPageContainer.

2022-03-14 20:40 UTC, rast-mk1 reviewed
What do you think about button having some kind of change in styling while it is being clicked? Not sure if this should be done in this PR, though.

2022-03-14 21:10 UTC, wlechowicz requested changes

2022-03-14 21:10 UTC, wlechowicz commented on app/components/Form/SignInForm/index.js
> +const emailPattern = /^[a-z\d]+[\w\d.-]*(\+[\w\d.-]*)?@(?:[a-z\d]+[a-z\d-]+\.){1,5}[a-z]{2,6}$/i;
This is too strict. Something more generic like "looks like an email more or less, so has at least 5 characters and contains @ and ."
We need to be that strict when registering the user, but when logging in we just want to be a little safe.

2022-03-14 23:11 UTC, marcelina-hasiak requested changes

2022-03-14 23:11 UTC, marcelina-hasiak commented on app/components/Form/SignInForm/SignInForm.styles.js
> +`;
I need it as well. I put this component inside Form folder in form.styles.js file for now.

2022-03-14 23:11 UTC, marcelina-hasiak commented on app/components/Form/SignInForm/index.js
> +    }
We have already validateFormInputs.js file below utils folder. It would be neat to move your validation there.

2022-03-15 13:12 UTC, wlechowicz commented on app/components/Form/SignInForm/index.js
> +    if (!isErrorOccured) {
Well no it can't, state updates are queued so we need to treat them as async, we can't assume those states changes synchronously like this. I suggested a different approach instead, with errors being collected in an array locally, before being set in state.

2022-03-15 22:26 UTC, weronika299 commented on app/components/Form/SignInForm/SignInForm.styles.js
> +`;
Ok, I did it also. We can do this in this way that the person who will merge as the second will delete it.

2022-03-16 00:11 UTC, wlechowicz commented on app/components/Form/SignInForm/index.js
> +    }
This validation should be much more relaxed than the sign up one, as explained on stand up.

2022-03-16 00:31 UTC, wlechowicz requested changes

2022-03-16 00:31 UTC, wlechowicz commented on app/components/Form/SignInForm/index.js
> +  const [inputErrors, setInputErrors] = useState(initialState);
Not a fan of this initial state for errors as explained in the sign up PR.

2022-03-16 00:31 UTC, wlechowicz commented on app/components/Form/SignInForm/index.js
> +    setInputErrors({ initialState });
Too many curly braces, initialState is an object already.

2022-03-16 00:31 UTC, wlechowicz commented on app/utils/validateFormInputs.js
> +    validationErrors.password = 'Enter at least 5 characters.';
'Password must contain at least 5 characters'.

2022-03-16 08:45 UTC, marcelina-hasiak approved these changes
With fixes on Wojtek's comments everything looks good ;)

2022-03-16 08:45 UTC, marcelina-hasiak commented on app/components/Form/SignInForm/index.js
> +    let validationErrors = validateSignInForm(inputValues.email, inputValues.password);
I would only adapt validateSignInForm to pass only obj inputValues and not its properties but it's just a suggestion.

2022-03-16 16:00 UTC, wlechowicz approved these changes

2022-03-16 17:10 UTC, merged