feat: backend movies/category/[id] endpoint #1737
intive/patronage22_poznan_js pull request #75
Opened 2022-03-15 23:21 UTC by rast-mk1

Test this endpoint using /api-doc. 

Outcome of possible use:
![obraz](https://user-images.githubusercontent.com/56893415/158488003-3599f216-8bd6-4470-8552-05633156f80c.png)

2022-03-16 23:09 UTC, wlechowicz requested changes

2022-03-16 23:09 UTC, wlechowicz commented on pages/api/movies/category/[id].js
> +    }
Since it's not a movie but a list, this const could have a more fitting name.

2022-03-16 23:09 UTC, wlechowicz commented on lib/services/movieDb.js
> +    data = Object.fromEntries(dataToCamelCase);
Since this code is duplicated here and in lines 54-55,, it should become a function that takes in the data to transform and returns a transformed object, like `return makeKeysCamelCase(movie);`

2022-03-16 23:09 UTC, wlechowicz commented on lib/services/movieDb.js
> +  const wholeUrl = `${baseUrl}/${url}?api_key=${token}&language=en-US${query}`;
If parameter `query` is not passed in (it's undefined), this will produce a string `&language=en-USundefined`. Default `query` parameter to an empty string in the function declaration.

2022-03-16 23:19 UTC, rast-mk1 commented on pages/api/movies/category/[id].js
> +    }
Agreed

2022-03-16 23:35 UTC, rast-mk1 commented on lib/services/movieDb.js
> +  const wholeUrl = `${baseUrl}/${url}?api_key=${token}&language=en-US${query}`;
Good call. Made changes.

2022-03-16 23:54 UTC, rast-mk1 commented on lib/services/movieDb.js
> +    data = Object.fromEntries(dataToCamelCase);
Done as requested.

2022-03-17 17:38 UTC, wlechowicz requested changes

2022-03-17 17:38 UTC, wlechowicz commented on lib/services/movieDb.js
>        return movie;
No need to assign to a variable, you can just `return makeKeysCamelCase(movie);`

2022-03-17 17:38 UTC, wlechowicz commented on lib/services/movieDb.js
> +    data = makeKeysCamelCase(data);
The `data` can stay a const and you can just `return makeKeysCamelCase(data);` here.

2022-03-17 17:38 UTC, wlechowicz commented on lib/services/movieDb.js
> +  return data;
Again, you can just `return Object.fromEntries(dataToCamelCase);`
Assigning to function parameters is not a good idea anyways.

2022-03-17 17:38 UTC, wlechowicz commented on lib/services/movieDb.js
> + * @param {string|number} query additional query
When is `query` a number?

2022-03-17 21:28 UTC, rast-mk1 commented on lib/services/movieDb.js
> + * @param {string|number} query additional query
At first, changes in movieDbClient were supposed to look differently and having query as number was an option. Forgot to change this after going for different approach.

2022-03-17 21:29 UTC, rast-mk1 commented on lib/services/movieDb.js
>        return movie;
True, made changes.

2022-03-17 21:30 UTC, rast-mk1 commented on lib/services/movieDb.js
> +    data = makeKeysCamelCase(data);
Yes, that's a good idea.

2022-03-17 21:30 UTC, rast-mk1 commented on lib/services/movieDb.js
> +  return data;
Sure. Made changes here.

2022-03-17 22:47 UTC, weronika299 approved these changes
I think that it looks good.

2022-03-18 12:04 UTC, wlechowicz approved these changes

2022-03-18 22:17 UTC, merged