feat: redesign MovieHero comp
intive/patronage22_poznan_js pull request #76
Opened 2022-03-16 16:33 UTC by wolnio

2022-03-16 18:45 UTC, wlechowicz commented on app/components/MovieHero/MovieHero.stories.js
> +const movieMockData = {
This would be passed in to all the stories, so you can add it to the Template like
`const Template = (args) => <MovieHero movieData={movieMockData} {...args} />;`

2022-03-16 18:55 UTC, wlechowicz commented on app/components/MovieHero/index.js
> +export default function MovieHero({ ...props }) {
`({ ...props })` does nothing, it's the same as `(props)`, you can destructure `({ movieData })` from the props.

2022-03-16 19:52 UTC, marcelina-hasiak requested changes

2022-03-16 19:52 UTC, marcelina-hasiak commented on app/components/MovieHero/MovieHero.styles.js
> +  height: 100vh;
<img width="300" alt="Zrzut ekranu 2022-03-16 o 20 26 02" src="https://user-images.githubusercontent.com/62512837/158674693-312322b1-732e-4753-a1ad-558e09545415.png">
It looks like HeroContents should be a sibling to Carousel component and HeroWrapper might have 100vh then.

2022-03-16 19:52 UTC, marcelina-hasiak commented on app/components/MovieHero/MovieHero.styles.js
> +  background: linear-gradient(180deg, rgba(32, 32, 32, 0) 0%, #1e1b26 75%, #1e1b26 100%);
This shady background bottom should be visible on desktop too. Look at designs. But I would move it to HeroWrapper. You can set multiple backgrounds, so one would be an image with grayish cover and the other one shady bottom

2022-03-16 19:52 UTC, marcelina-hasiak commented on app/components/MovieHero/MovieHero.styles.js
> +    top: 268px;
Perhaps you won't need it at all when Carousel be placed.

2022-03-16 19:52 UTC, marcelina-hasiak commented on app/components/MovieHero/MovieHero.styles.js
> +  //TO CONSIDER:text color could change to white or black based on actual background color
You can't take control over every movie image from API. To secure yourself from low contarst ratio please consider adding some cover on your hero image -> linear gradient

2022-03-16 19:52 UTC, marcelina-hasiak commented on app/components/MovieHero/index.js
> +export default function MovieHero({ ...props }) {
or: `({movieData: {release_date, popularity, vote_average}})`

2022-03-16 20:00 UTC, rast-mk1 commented on app/components/MovieHero/MovieHero.styles.js
> +  background: linear-gradient(180deg, rgba(32, 32, 32, 0) 0%, #1e1b26 75%, #1e1b26 100%);
> background: linear-gradient(180deg, rgba(32, 32, 32, 0) 0%, #1e1b26 75%, #1e1b26 100%);

I don't know how does this affect MovieHero's look. Is it needed at all?

2022-03-16 20:08 UTC, wlechowicz commented on app/components/MovieHero/MovieHero.styles.js
> +  height: 100vh;
That's an editorial carousel that looks different from other carousels and we don't have that in our app.

2022-03-16 20:09 UTC, wlechowicz commented on app/components/MovieHero/MovieHero.styles.js
> +  //TO CONSIDER:text color could change to white or black based on actual background color
Better than background, an outline would make the text perfectly visible against any background - I knew meme making experience will come in handy one day - black outline, white text.
To add a text outline, try this: https://stackoverflow.com/questions/4919076/outline-effect-to-text

2022-03-16 21:41 UTC, weronika299 requested changes

2022-03-16 21:41 UTC, weronika299 commented on app/components/MovieHero/MovieHero.styles.js
> +    margin-bottom: 8px;
I think that you should use font-size 1.25em on desktop.

2022-03-17 05:22 UTC, wolnio commented on app/components/MovieHero/MovieHero.styles.js
> +  //TO CONSIDER:text color could change to white or black based on actual background color
Yeah, I've read about it, but as you said it would look strange. I'm going to try Outline as Wojtek mentioned 🤷🏼

2022-03-17 05:24 UTC, wolnio commented on app/components/MovieHero/MovieHero.styles.js
> +  background: linear-gradient(180deg, rgba(32, 32, 32, 0) 0%, #1e1b26 75%, #1e1b26 100%);
On mobile it gives a little gradient on the bottom of the page. It can be easily seen in the design.

2022-03-17 09:24 UTC, rast-mk1 commented on app/components/MovieHero/MovieHero.styles.js
> +  background: linear-gradient(180deg, rgba(32, 32, 32, 0) 0%, #1e1b26 75%, #1e1b26 100%);
OK, I see it now. Nice!

2022-03-17 17:50 UTC, wolnio commented on app/components/MovieHero/MovieHero.styles.js
> +  background: linear-gradient(180deg, rgba(32, 32, 32, 0) 0%, #1e1b26 75%, #1e1b26 100%);
You are right, I did see that it's also implemented on desktop too, but thought that maybe it can be set as carousel background. But it makes more sense to set that gradient on MovieHero.

2022-03-20 21:22 UTC, wlechowicz requested changes

2022-03-20 21:22 UTC, wlechowicz commented on app/components/MovieHero/MovieHero.stories.js
> +  vote_average: 8.4,
Please update to mach the current camleCaseKeys in movie and list data.

2022-03-20 21:22 UTC, wlechowicz commented on app/components/MovieHero/MovieHero.stories.js
> +};
Don't need this anymore since you're passing it directly to Template.

2022-03-20 21:22 UTC, wlechowicz commented on app/components/MovieHero/index.js
> +    <HeroWrapper backgroundImg={'https://image.tmdb.org/t/p/original' + movieData.backdrop_path}>
This comes formatted with the data already, so you need to adjust this as well.

2022-03-20 21:30 UTC, wolnio commented on app/components/MovieHero/index.js
> +    <HeroWrapper backgroundImg={'https://image.tmdb.org/t/p/original' + movieData.backdrop_path}>
I know, you've wrote that in the latest review, although I had problems with swagger and couldn't see correct returned data. Even though wanted to make a new commit and add proper path later 🥸

2022-03-22 17:12 UTC, weronika299 approved these changes

2022-03-24 16:20 UTC, marcelina-hasiak approved these changes

2022-03-24 16:26 UTC, marcelina-hasiak approved these changes
Everything looks good except for text-shadow you use - I don't like the effect. I would use something like `text-shadow: 1px 2px 5px black`. Nevertheless PR approved from my side. 
<img width="300" alt="Zrzut ekranu 2022-03-24 o 17 20 00" src="https://user-images.githubusercontent.com/62512837/159963076-d319668c-64e6-4733-894c-e47987eab545.png">

2022-03-24 17:32 UTC, wlechowicz approved these changes

2022-03-26 15:08 UTC, merged