Feature/P-1746 modal for users movie
intive/patronage22_poznan_js pull request #80
Opened 2022-03-17 22:57 UTC by hiimsagan

2022-03-18 02:04 UTC, wlechowicz requested changes

2022-03-18 02:04 UTC, wlechowicz commented on app/components/Modal/index.js
> +};
These don't belong here, they are not props of the Modal.

2022-03-18 02:04 UTC, wlechowicz commented on pages/index.js
> +      {state.isModalOpen && <Modal content={state.content} />}
You can destructure these from state. Also `content` is very g eneric, please rename to `modalContent`.

2022-03-18 11:07 UTC, rast-mk1 commented on pages/index.js
> +      {state.isModalOpen && <Modal content={state.content} />}
1. Should there be a button to enable modal or should modal be already there when page loads? Or does it look like that just for testing?
2. Probably you could use `<Image />` instead of `<MoviePoster />` and have URL for higher quality backdrop instead of poster, e.g. https://image.tmdb.org/t/p/w780/qcCo2yV6xoak7tMI9YfGSoJgxKW.jpg

2022-03-18 12:57 UTC, hiimsagan commented on pages/index.js
> +      {state.isModalOpen && <Modal content={state.content} />}
is just for testing

2022-03-18 15:59 UTC, weronika299 requested changes

2022-03-18 15:59 UTC, weronika299 commented on app/components/Modal/Modal.stories.js
> +export const Default = Template.bind({});
Wouldn’t it be better if you add: Default.parameters = {
  viewport: {
    defaultViewport: 'responsive',
  },
};
?

2022-03-18 15:59 UTC, weronika299 commented on app/components/Modal/Modal.styles.js
> +  }
You probably forgot to remove it.

2022-03-18 20:54 UTC, wlechowicz commented on app/components/Modal/index.js
> +import { GlobalStyle } from 'components/Header/Header.styles';
Extract it somewhere then, this component should have no dependency on Header.

2022-03-18 21:45 UTC, hiimsagan commented on app/components/Modal/Modal.styles.js
> +  }
Yes i forgot but is done now

2022-03-18 21:45 UTC, hiimsagan commented on app/components/Modal/Modal.stories.js
> +export const Default = Template.bind({});
Done

2022-03-18 23:29 UTC, marcelina-hasiak requested changes
It looks good overall, just please rename GlobalStyle component

2022-03-18 23:29 UTC, marcelina-hasiak commented on app/components/Modal/Modal.styles.js
> +  z-index: 1001;
I'm not a fun of setting `z-index: over 9000`; `z-index: multiply of 10` makes out too, but I don't know what's best. @wlechowicz any advice?

2022-03-18 23:29 UTC, marcelina-hasiak commented on app/components/Modal/Modal.stories.js
> +  title: 'Modal/modal',
Every Component in Storybook is written uppercase, you could adjust yours ;)

2022-03-19 18:19 UTC, hiimsagan commented on app/components/Modal/Modal.styles.js
> +  z-index: 1001;
i have to do that  becouse when modal is open you can do anthing in simple header

2022-03-19 18:22 UTC, hiimsagan commented on app/components/Modal/Modal.styles.js
> +  bottom: 0;
oo thans for that ;)

2022-03-19 18:26 UTC, wlechowicz commented on app/components/Modal/Modal.styles.js
> +  z-index: 1001;
Well 1 2 3 4 5 wouldn't be a safe approach, and since it's a modal that's supposed to cover ALL of the app underneath, it should be way over anything we have in the app, so if the app occupies indexes in the first hundred, then it's fine to start the modal at 1000. The header shouldn't be 999 then, I suppose.

2022-03-19 18:27 UTC, wlechowicz commented on app/components/Modal/Modal.stories.js
> +  title: 'Modal/modal',
Akshully, not UPPERCASE, but PascalCase.

2022-03-19 18:54 UTC, marcelina-hasiak commented on app/components/Modal/Modal.stories.js
> +  title: 'Modal/modal',
Indeed ^^'

2022-03-19 19:02 UTC, hiimsagan commented on app/components/Modal/Modal.styles.js
> +  z-index: 1001;
If you open modal, when you are not logged you can click in every things in simplehaeder i dont know if modal will be open when you are not logged.
I could change `z-index` in simple haeder, and then i dont have to set `  z-index: 1001`

2022-03-19 19:04 UTC, hiimsagan commented on app/components/Modal/Modal.stories.js
> +  title: 'Modal/modal',
Done

2022-03-19 19:05 UTC, hiimsagan commented on app/consts/bodystyles.js
> +export const GlobalStyle = createGlobalStyle`
yee i change that

2022-03-19 23:12 UTC, wlechowicz approved these changes

2022-03-20 05:58 UTC, marcelina-hasiak approved these changes

2022-03-20 05:58 UTC, marcelina-hasiak commented on app/components/Modal/Modal.styles.js
> +  z-index: 1001;
Modal: 1000; 
Button inside modal: it doeasn't need z-index at all, I suppose;
Header: 100?
It's only suggestion.

2022-03-20 12:56 UTC, weronika299 approved these changes

2022-03-20 13:07 UTC, merged