feat: add Signup page logic #619
intive/patronage22_poznan_js pull request #88
Opened 2022-03-21 22:48 UTC by marcelina-hasiak

2022-03-21 23:42 UTC, wlechowicz requested changes
One thing I can't comment inline, is that the field in form should say "address" rather than "adress".

2022-03-21 23:42 UTC, wlechowicz commented on app/components/Form/UserSignUpForm/index.js
> +      setRegisterError('Something went wrong');
'Oops! Something went wrong. Please try again later.'

2022-03-21 23:42 UTC, wlechowicz commented on app/components/Form/UserSignUpForm/index.js
> +          {'Now you can '}
'Success! Now you can _sign in_!'

2022-03-21 23:42 UTC, wlechowicz commented on app/components/Form/UserSignUpForm/index.js
> +  }, [isFormSubmitting, registerError]);
This doesn't seem necessary anymore.

2022-03-21 23:42 UTC, wlechowicz commented on app/components/Form/UserSignUpForm/index.js
> +      response.json().then((data) => setRegisterError(data.error));
This isn't necessarily a good idea. You should handle 400 and 409 differently and with custom error messages.

Cases for 400 are
- missing required fields (payload error)
- invalid values or those fields (validation error)

both of which are an oopsie on your side, not a user fault, so user should see "Oppsie! Something went wrong but it shouldn't have and it's totally not your fault but ours and we've dispatched our most skilled team of monkeys to bang on it with a hammer" type of message.

409 is plain and simple but "Email already in use" is kinda rough. Something like "Email address already in use. Try _signing in_ instead!".
You know, smile and wave, just smile and wave.

2022-03-21 23:42 UTC, wlechowicz commented on app/components/Form/UserSignUpForm/UserSignUpForm.styles.js
> +`;
The style of these messages should be uniform across sign in and sign up. Yes, that means a common component under Form.

2022-03-21 23:42 UTC, wlechowicz commented on app/components/Form/UserSignUpForm/index.js
> +    if (status === 404) router.push('/404');
404 after signup? If it ever happens - which it shouldn't - then it should not take the user to 404 page, because "I just clicked a button, why does it say not found?" but display an oopsie error.

2022-03-21 23:42 UTC, wlechowicz commented on app/components/Form/UserSignUpForm/index.js
> +      {registerError && !isFormSubmitting && (
`&& !isFormSubmitting` is duplicated, which means it should be like
`{!isFormSubmitting && { registerError ? something : something else }}`

2022-03-21 23:42 UTC, wlechowicz commented on app/components/Pages/404/index.js
> +          src={appLogo404Img}
Nice touch, might be more fitting for the 500 cases, but I like the extra thought :)

2022-03-21 23:42 UTC, wlechowicz commented on app/utils/fetchWrapper.js
> +  return response;
No point in awaiting just to return it, since it would have to be awaited again anyway. Also nice wrapper, but fetch might need to be wrapped in try..catch. And it could also do the res.json() while we're at it, and then `return { ok: res.ok, json };`. This would turn it from "post JSON get Response" into "post JSON get JSON".

2022-03-22 16:00 UTC, rast-mk1 commented
In general, I like it.
Something not related to this specific PR, but Form itself: when there is something typed in and you hit refresh, labels and values are mixed together.

2022-03-22 16:21 UTC, wlechowicz commented
> In general, I like it. Something not related to this specific PR, but Form itself: when there is something typed in and you hit refresh, labels and values are mixed together.

Also happens with auto-fill. Let's refine this once QA reports it.

2022-03-22 16:58 UTC, marcelina-hasiak commented on app/components/Form/UserSignUpForm/index.js
> +  }, [isFormSubmitting, registerError]);
Do you mean timeout? But what about case where the response is too quick? I need to extend animation to prevent glitch.

2022-03-22 17:42 UTC, weronika299 reviewed
I have only one suggestion. What do you think about changing style of ServersideMessage: 'Now you can sign in'? I think the 'sign in' link could have a slightly different color than the rest of the message.

2022-03-22 22:15 UTC, wlechowicz commented on app/components/Form/UserSignUpForm/index.js
> +  }, [isFormSubmitting, registerError]);
Ah I see, forgot about that. Boomer brain.

2022-03-22 22:16 UTC, wlechowicz commented
> I have only one suggestion. What do you think about changing style of ServersideMessage: 'Now you can sign in'? I think the 'sign in' link could have a slightly different color than the rest of the message.

Definitely links need to stand out from the rest of the text in all cases, they can be underlined (default a style).

2022-03-24 22:10 UTC, hiimsagan requested changes
I thnik you forgot to show error massage

![obraz_2022-03-24_230756](https://user-images.githubusercontent.com/83120643/160018292-ba93248a-0f0d-4b93-8ae1-ae29781e9409.png)

2022-03-26 20:10 UTC, marcelina-hasiak commented
> I have only one suggestion. What do you think about changing style of ServersideMessage: 'Now you can sign in'? I think the 'sign in' link could have a slightly different color than the rest of the message. 
It's already underlined, bold and uppercase. Do we need more?

> ![obraz_2022-03-24_230756](https://user-images.githubusercontent.com/83120643/160018292-ba93248a-0f0d-4b93-8ae1-ae29781e9409.png)
I know, I know. TY

2022-03-26 21:39 UTC, wlechowicz requested changes

2022-03-26 21:39 UTC, wlechowicz commented on app/components/Form/UserSignUpForm/index.js
>  Object.freeze(initialState);
```suggestion
const initialState = Object.freeze({ email: '', password: '', username: '' });
```

2022-03-26 21:39 UTC, wlechowicz commented on app/components/Form/UserSignUpForm/index.js
> +          setInputValues(initialState);
As I mentioned many times, clearing form on submit error is super annoying to the user, because they must retype everything even if just one field was bad.

2022-03-26 21:39 UTC, wlechowicz commented on app/components/Form/UserSignUpForm/index.js
> +        (registerError ? (
That's a bit confusing, `registerError` null means there was no error or nothing was done, any other value means there was an error except for an empty string that means success? It would be easier to have an explicit success flag rather than this combination of `not submitting combined with an error but it actually means success`.

2022-03-26 21:39 UTC, wlechowicz commented on app/components/Form/UserSignUpForm/index.js
> +          </ServersideMessage>
I suggested a different solution with an outline instead. You can extrapolate that with a green outline and another prop that makes shows the outline and success message.

2022-03-26 21:39 UTC, wlechowicz commented on app/utils/fetchWrapper.js
> +    return { status: response.status, data: response.json() };
Hmm does this work? The function `post` will return a Promise that resolves to this object with `status` and `data`, but `data` will still be a Promise of the `json()` method result.
You should await the JSON to be parsed like 
```
 const data = await response.json();
 return { status: response.status, data };
```

2022-03-27 13:44 UTC, marcelina-hasiak commented on app/components/Form/UserSignUpForm/index.js
> +          setInputValues(initialState);
I know, I added this code recently, because this is how it works on merged sign-in - I thought this is the way.

2022-03-27 13:47 UTC, marcelina-hasiak commented on app/utils/fetchWrapper.js
> +    return { status: response.status, data: response.json() };
Yep, my mistake. I don't use data inside sign-up so I didn't catch it.

2022-03-27 14:04 UTC, marcelina-hasiak commented on app/components/Form/UserSignUpForm/index.js
> +        (registerError ? (
I don't like it as well - it's not readable, but I didn't know how to merge in one all these logical statements.

2022-03-27 21:31 UTC, wlechowicz requested changes
Good improvements from last review! Couple of things I spotted are inline.

2022-03-27 21:31 UTC, wlechowicz commented on app/components/Form/ServerSideMessage/index.js
> +    <StyledServerSideMessage errorType={errorType} {...props}>
`errorType` is misleading, seems to suggest that the prop contains information about the type of error, while in fact it's a boolean and should be called `hasError` or `isError`, the former being the one used elsewhere so I'd stick to that.

2022-03-27 21:31 UTC, wlechowicz commented on app/components/Form/ServerSideMessage/index.js
> +      <ServerSideMessageIcon type={errorType ? 'x-mark' : 'check-mark'} />
An improvement to this would be to encapsulate this icon type logic in the component itself, like this
```
export const ServerSideMessageIcon = styled(Icon).attrs(
  ({ hasError }) => ({ type: hasError ? 'x-mark' : 'check-mark' })
)`
  padding: 0 5px;
`;
```

2022-03-27 21:31 UTC, wlechowicz commented on app/components/Form/UserSignUpForm/index.js
> +  const onError = Boolean(!isFormSubmitting && registerError);
Booleans, so names should start with `is` or `has`.

2022-03-28 06:25 UTC, marcelina-hasiak commented on app/components/Form/ServerSideMessage/index.js
> +      <ServerSideMessageIcon type={errorType ? 'x-mark' : 'check-mark'} />
Thank you for this one. I should have read SC documentation more :|

2022-03-28 17:22 UTC, wlechowicz commented on app/components/Form/UserSignUpForm/index.js
> +          setInputValues(initialState);
It is not and sign-in needs fixing if it does that.

2022-03-28 17:26 UTC, wlechowicz requested changes

2022-03-28 17:26 UTC, wlechowicz commented on app/components/Form/ServerSideMessage/ServerSideMessage.stories.js
> +  errorType: false,
Forgot to change prop names in story.

2022-03-28 17:34 UTC, wlechowicz approved these changes

2022-03-28 18:33 UTC, hiimsagan approved these changes

2022-03-28 20:18 UTC, merged