Feat: Movie Details component #1747
intive/patronage22_poznan_js pull request #89
Opened 2022-03-21 22:48 UTC by hiimsagan

2022-03-24 21:17 UTC, marcelina-hasiak requested changes

2022-03-24 21:17 UTC, marcelina-hasiak commented on app/components/MovieDetails/styles.js
> +export const InfoComponent = styled.div`
This component isn't prepared for getting dynamic data. I duplicated movie description and it here's the outcome.
<img width="300" alt="image" src="https://user-images.githubusercontent.com/62512837/160009050-dc011da7-a846-4cfa-a459-aa50d0989ef4.png">
Here's the random snippet I've found, investigate it and edit if needed: 
```
   overflow: hidden;
   text-overflow: ellipsis;
   display: -webkit-box;
   -webkit-line-clamp: 2; /* number of lines to show */
           line-clamp: 2; 
   -webkit-box-orient: vertical;
```
Please remember to increase line-height, text isn't much readable now. (1.4 from design is good ;))

2022-03-24 21:17 UTC, marcelina-hasiak commented on app/components/MovieDetails/styles.js
> +  }
It looks like your styles won't overwrite the styles from component, simply extend it by export const SomeName = styled(Button)`styles here`

2022-03-24 21:17 UTC, marcelina-hasiak commented on app/components/MovieDetails/styles.js
> +`;
One more thing: en empty space on the right side of modal. Are we able to pull data about the actors and actress?

2022-03-24 21:17 UTC, marcelina-hasiak commented on app/components/MovieDetails/styles.js
> +export const TitleWrapper = styled.div`
It's title so use heading tag

2022-03-24 22:18 UTC, hiimsagan commented on pages/index.js
> +        <Button onClick={() => openModal(<MovieDetails movieId={11} isButton />)}>OpenModal</Button>
This is just to show Case generally yoy will click in movieCard in carousel and you will open modal with info

2022-03-24 22:31 UTC, wlechowicz commented on app/components/MovieDetails/index.js
> +        const resp = await fetch(`/api/movies/${movieId}`);
When you want to get data on backend (server-side rendering), for example in getServerSideProps on your page, then you use a method like getMovieById from movieDb service. Data will fetched and rendered in props, then page will be rendered.
When you want to get the same data on frontend (in browser), you have to fetch the data from an API endpoint, like api/movies/[id].
This component works with both, it either receives the data through props from page (preloadedMovieData) if it's being used on a page, or it fetches the data itself when it's used in a modal after user clicks MovieCard in carousel (on frontend).

2022-03-24 22:36 UTC, wlechowicz commented on app/components/MovieDetails/styles.js
> +export const InfoComponent = styled.div`
Definitely not ellipsis, we want to show the whole description. The component should just grow vertically to accommodate its content.

2022-03-24 22:45 UTC, marcelina-hasiak commented on app/components/MovieDetails/index.js
> +        const resp = await fetch(`/api/movies/${movieId}`);
All clear now, ty.

2022-03-26 14:41 UTC, weronika299 requested changes

2022-03-26 14:41 UTC, weronika299 commented on app/components/MovieDetails/styles.js
> +export const Headingg = styled.h2`
Could you rename this component?

2022-03-26 14:41 UTC, weronika299 commented on app/components/MovieDetails/ProductionCompanies.js
> +  console.log(productionCompanies);
Could you remove this console.log?

2022-03-26 14:41 UTC, weronika299 commented on app/components/MovieDetails/ProductionCompanies.js
> +    console.log(companie.name);
And this console.log

2022-03-26 14:41 UTC, weronika299 commented on app/components/MovieDetails/ProductionCompanies.js
> +  const companies = productionCompanies.map((companie) => {
typo => company

2022-03-26 14:41 UTC, weronika299 commented on app/components/MovieDetails/ProductionCompanies.style.js
> +  font-size: 14px;
Could you change it to rem?

2022-03-26 14:41 UTC, weronika299 commented on app/components/MovieDetails/styles.js
> +
Could you rename this file to MovieDetails.styles.js?

2022-03-26 17:15 UTC, wlechowicz requested changes
No stories, for any of the components added. File structure is wrong, subcomponents of MovieDetails should be put in their own subfolders under MovieDetails like components/MovieDetails/ProductionCompanies/index.js with their own styles and stories, if applicable.

2022-03-26 17:37 UTC, wlechowicz requested changes
Bunch of odd stuff in CSS that's hard to judge if it makes sense, since there's no stories attached.

2022-03-26 17:37 UTC, wlechowicz commented on app/components/Modal/Modal.styles.js
> +  overflow-x: auto;
This is wrong, should be `overflow-y` AKA vertical overflow.

2022-03-26 17:37 UTC, wlechowicz commented on app/components/MovieDetails/ProductionCompanies.style.js
> +import styled from 'styled-components';
This file should be named `.styles.js` not .style.js`

2022-03-26 17:37 UTC, wlechowicz commented on app/components/MovieDetails/TitileComponent.js
> +import { TitleWrapper, Headingg } from './styles';
`Titile` `Headingg`

2022-03-26 17:37 UTC, wlechowicz commented on app/components/MovieDetails/TitileComponent.js
> +      </Button>
Isn't this the same button as in MovieHero? You can make this Icon a styled component like 
```
export const PlayIcon = styled(Icon).attrs({ type: 'caret-right' })`
  margin-right: 1rem; 
`;
```

2022-03-26 17:37 UTC, wlechowicz commented on app/components/MovieDetails/index.js
> +  return (
You're not doing anything with the `preloadedMovieData` - if it was present in props, you would not render anything because it would stop you from fetching but you didn't use it to render anything.

2022-03-26 17:37 UTC, wlechowicz commented on app/components/MovieDetails/index.js
> +              <ProductionCompanies productionCompanies={movieData.productionCompanies} />
These props should be destructured from `movieData` beforehand.

2022-03-28 22:50 UTC, rast-mk1 commented on app/components/MovieDetails/styles.js
> +`;
Cast and crew comes from `/movie/{movie_id}/credits` that is not yet (will ever be @wlechowicz ?) used in our project. https://developers.themoviedb.org/3/movies/get-movie-credits

2022-03-29 20:47 UTC, weronika299 requested changes

2022-03-29 20:47 UTC, weronika299 commented on app/components/MovieDetails/Companies/ProductionCompanies.style.js
> +  font-size: 14px;
rem for font-size

2022-03-29 20:47 UTC, weronika299 commented on app/components/MovieDetails/index.js
> +    <>
Do you need this empty tag?

2022-03-29 20:47 UTC, weronika299 commented on app/components/MovieDetails/MovieDetails.stories.js
> +import { useState } from 'react';
Maybe it's better to import {useState} at the beginning?

2022-03-30 08:23 UTC, lenasokolova commented on app/components/MovieDetails/Heading/TitleComponent.style.js
> +  padding-top: 20px;
you're using padding first and then overwriting it by padding-top.

```suggestion
  padding: 20px 16px 8px;
```

2022-03-30 08:23 UTC, lenasokolova commented on app/components/MovieDetails/MovieDetails.styles.js
> +    padding-bottom: 20px;
here's the same stuff as above in TitleComponent.style.js.
```suggestion
    padding: 0 72px 20px;
```

2022-03-30 16:22 UTC, wlechowicz requested changes
File names and component folders and files mismatch issues still unresolved.

2022-03-30 17:49 UTC, weronika299 commented on app/components/MovieDetails/ProductionCompanies/index.js
> +    return <StyledItem key={companie.id}>{companie.name}</StyledItem>;
typo => company

2022-03-30 17:51 UTC, weronika299 commented on app/components/MovieDetails/Heading/Heading.style.js
> +
also Heading.styles.js

2022-03-30 19:21 UTC, wlechowicz requested changes
- Heading stories make no sense
- there's a horizontal line between containers, probably 2 adjacent flex elements with non-zero margin (see image)
- where's the carousel of similar movies?

![image](https://user-images.githubusercontent.com/24250766/160914254-62d77859-5481-4934-b1f9-b1f637b910a2.png)

2022-03-30 19:37 UTC, lenasokolova approved these changes

2022-03-30 20:23 UTC, weronika299 approved these changes
I agree with @wlechowicz comments and I don't see nothing more.

2022-03-31 16:30 UTC, wlechowicz commented
`TypeError: movies.map is not a function` from Carousel in your stories. Seems you're not passing in the movies list properly.

2022-04-02 17:49 UTC, marcelina-hasiak requested changes

2022-04-02 17:49 UTC, marcelina-hasiak commented on app/components/MovieDetails/index.js
> +            <Carousel movies={similarMoviesData} />
Perhaps some mapping over these components? But not 100% sure. I remember we talked about putting carousel title inside carousel component... @wlechowicz What's your advice here?

2022-04-02 17:49 UTC, marcelina-hasiak commented on app/components/MovieDetails/index.js
> +  const [movieData, setMovieData] = useState('');
You don't expect movieData to be string, set initial state to empty object/null

2022-04-03 20:15 UTC, hiimsagan commented on app/components/MovieDetails/index.js
> +  const [movieData, setMovieData] = useState('');
OK there is small issue when i set movieData on null or object will will get
![null](https://user-images.githubusercontent.com/83120643/161446477-7588bb67-f94b-4fd4-8361-8b03c92954cf.png)
or
![object](https://user-images.githubusercontent.com/83120643/161446525-b2fc8b76-cd73-46c7-bbe7-c08e1c390edc.png)
@wlechowicz  in his review write me to destructured props from movieData to pass them in otheres components.
@marcelina-hasiak any advice what should i do ?

2022-04-04 20:29 UTC, hiimsagan commented on app/components/MovieDetails/Heading/Heading.styles.js
> +`;
Done

2022-04-04 21:03 UTC, hiimsagan commented on app/components/MovieDetails/index.js
> +            <Carousel movies={similarMoviesData} />
Yes that would be good but i can't get list title and id from api

2022-04-04 22:23 UTC, wlechowicz commented on app/components/MovieDetails/index.js
> +            <Carousel movies={similarMoviesData} />
We did talk about it but it didn't happen so this is correct as of now.

2022-04-04 22:32 UTC, wlechowicz requested changes

2022-04-04 22:32 UTC, wlechowicz commented on app/components/MovieDetails/index.js
> +      }, 500);
Why is this in a timeout?

2022-04-04 22:32 UTC, wlechowicz commented on app/components/MovieDetails/index.js
> +    }
You don't need to copy props into state.

2022-04-04 22:32 UTC, wlechowicz commented on app/components/MovieDetails/index.js
> +        setRecommendedMoviesData(recomandationData);
Each of the 3 data sets - movie data and both carousels - could be fetched in parallel, there's no reason to do it all in one place. `if this data is not in props, then fetch it` times 3.

2022-04-04 22:32 UTC, wlechowicz commented on app/components/MovieDetails/index.js
> +      {movieData ? (
This is your problem, `movieData` will be truthy for an empty object. Use `movieData?.id` instead, or destructure it in line 32 and use here.

2022-04-04 22:32 UTC, wlechowicz commented on app/components/MovieDetails/index.js
> +  }, []);
```suggestion
  }, [movieId]);
```

2022-04-06 18:06 UTC, wlechowicz commented on app/components/MovieDetails/index.js
> +        setRecommendedMoviesData(recomandationData);
Nothing changed here.

2022-04-06 18:08 UTC, wlechowicz commented
How does this work? In preview, when clicking any movie on any carousel on home page, I get a 404 page, not movie details in a modal.

2022-04-07 12:10 UTC, marcelina-hasiak reviewed
I left some comments in previous revision with no reply from your side. I know they're minor but it would be nice to have a response. Nevertheless take care of logic ( listed by Wojtek ) first.

2022-04-14 18:12 UTC, marcelina-hasiak requested changes

2022-04-14 18:12 UTC, marcelina-hasiak commented on app/components/MovieDetails/index.js
> +      setMovieData(preloadedMovieData);
Hmmmm do you need to put preloadedMovieData in state? You can always initialize it as initial state.

2022-10-11 10:58 UTC, closed without merging