feat: my list backend #1734
intive/patronage22_poznan_js pull request #94
Opened 2022-03-25 03:17 UTC by rast-mk1

**Work in progress**

Should run properly at the moment, with most requirements met.

TODO: 
- improve code quality, work on code duplication,
- add HTTP status 400 if `movieId` not in scope 0-50,
- use `Set` and `Array.filter`
- improve docs,
- apply `try catch`

2022-03-25 11:43 UTC, wlechowicz commented
> create client (like services/movieDb.js) 

Yes, pages will need to use a method, rather than an API endpoin, to fetch My List data.

2022-03-25 12:07 UTC, wlechowicz requested changes

2022-03-25 12:07 UTC, wlechowicz commented on pages/api/mylist/[movieId].js
> +    const command = { $pull: { items: movieId } };
If this works, then it's better, since it's a single operation.
With Array.filter you'd need to get the data, modify it and save back to DB with 2 operations.

2022-03-25 12:07 UTC, wlechowicz commented on pages/api/mylist/[movieId].js
> +    const command = { $addToSet: { items: movieId } };
This is better than Set in JS, since it's a single operation instead of get-modify-save.
Only issue is 
> [$addToSet](https://www.mongodb.com/docs/manual/reference/operator/update/addToSet/#mongodb-update-up.-addToSet) does not guarantee a particular ordering of elements in the modified set.

which might mean we don't preserve order of My List. See if it's true, if it preserves the order then keep it.

2022-03-25 12:55 UTC, rast-mk1 commented on pages/api/mylist/[movieId].js
> +    const command = { $addToSet: { items: movieId } };
Did some test using few users and seems like order doesn't change.

2022-03-25 12:57 UTC, rast-mk1 commented on pages/api/mylist.js
> +    const list = await db.collection('user_lists').findOne({ _id: req.session.id });
I did that on purpose, to have rather one `_id` than auto generated `_id` and then `user_id` as well. Should I have both `_id` and `user_id`?

2022-03-25 13:00 UTC, rast-mk1 commented on pages/api/mylist.js
> +    return res.status(200).json(list?.items);
Got it.

2022-03-25 13:01 UTC, rast-mk1 commented on pages/api/mylist/[movieId].js
> +    const userList = await db.collection('user_lists').findOne({ _id: req.session.id });
Oversight. Will fix that.

2022-03-25 13:04 UTC, rast-mk1 commented on pages/api/mylist/[movieId].js
> +    if (!userList && movieId.length > 0 && movieId.length < 50) {
It does work like intended, though. Will look into that.

2022-03-25 13:08 UTC, rast-mk1 commented on pages/api/mylist/[movieId].js
> +    } else if (movieId.length > 0 && movieId.length < 50 && numberOfMoviesOnList < 50) {
I did that, because it worked fine for existing list, but I was getting HTTP 500 if there was no list (no `movieId.length`).

2022-03-25 13:09 UTC, rast-mk1 commented on pages/api/mylist/[movieId].js
> +    const command = { $pull: { items: movieId } };
It works.

2022-03-25 13:09 UTC, wlechowicz commented on pages/api/mylist.js
> +    const list = await db.collection('user_lists').findOne({ _id: req.session.id });
While we can use `_id`s for document relations between collections (and consider `user.id` redundant), we should keep them autogenerated as ObjectIds. But then we need to change what we return from sign in.
Also, using `user.id` as `_id` in a different collection doesn't sound like a good idea, since it will not scale - day will come when you need to add another collection related to user and you can't reuse the same logic because it would lead to duplicate `_id`s. Correct me if I'm wrong, but `_id` must be unique to the document across all collections in a database and we should express relationships between collections as a secondary field in the document. Unless you want to nest documents in other documents (like a document contains a list of child-documents) - then you would use `_id`.
I think using `user.id` generated by us makes it more DB-agnostic and lets the engine manage document id uniqueness.

2022-03-25 13:22 UTC, rast-mk1 commented on pages/api/mylist.js
> +    const list = await db.collection('user_lists').findOne({ _id: req.session.id });
Okay, that makes sense and having another `id` won't really complicate anything, so I am for it.

2022-03-26 17:20 UTC, wlechowicz commented on pages/api/mylist/[movieId].js
> +    } else if (movieId.length > 0 && movieId.length < 50 && numberOfMoviesOnList < 50) {
`movieId` is not the list, it's the input param from query.

2022-03-26 17:22 UTC, wlechowicz commented on pages/api/mylist/[movieId].js
> +    if (!userList && movieId.length > 0 && movieId.length < 50) {
It cannot work like intended, because `movieId` is not the list, it's the input param from query, so it's a numerical string between 0 and something so the length will always be between 0 and 50.

2022-03-27 18:45 UTC, rast-mk1 commented on docs/apiDocs.yml
> +      description: Insert movie into user's movie list.
Changed summary and description like suggested.

2022-03-27 18:57 UTC, rast-mk1 commented on pages/api/mylist/[movieId].js
> +    if (!userList && movieId.length > 0 && movieId.length < 50) {
Sorry, I got things mixed up a bit. I am limiting `movieId` length as suggested in improvements task from backlog: https://tracker.intive.com/jira/browse/P2022-1870 The goal is not to handle inputs with 50 or more digits, but I am willing to take different approach or remove this limit if needed.

2022-03-27 18:59 UTC, rast-mk1 commented on pages/api/mylist/[movieId].js
> +    } else if (movieId.length > 0 && movieId.length < 50 && numberOfMoviesOnList < 50) {
Yes, my bad. I meant `numberOfMoviesOnList ` not `movieId.length`,

2022-03-28 16:38 UTC, wlechowicz commented on pages/api/mylist/[movieId].js
> +    if (!userList && movieId.length > 0 && movieId.length < 50) {
Well the length limitation is for string params, this is a number and a number that has 50 digits is very well over the id limit we actually need.

2022-03-28 23:44 UTC, wlechowicz requested changes

2022-03-28 23:44 UTC, wlechowicz commented on app/server/services/myListClient.js
> + * @param {string|number} req Request containing user's session id
`req` is neither a string nor a number.

2022-03-28 23:44 UTC, wlechowicz commented on app/server/services/myListClient.js
> +  }
Use `Array.map` on `userList` for this, but make sure it's a valid result first.

2022-03-28 23:44 UTC, wlechowicz commented on docs/apiDocs.yml
> +      security: []
Not right, it is secured with auth.

2022-03-28 23:44 UTC, wlechowicz commented on docs/apiDocs.yml
> +          description: ""
Why empty?

2022-03-28 23:44 UTC, wlechowicz commented on docs/apiDocs.yml
> +      security: []
Nope, this is secure as well.

2022-03-28 23:44 UTC, wlechowicz commented on docs/apiDocs.yml
> +          description: ""
Empty.

2022-03-28 23:44 UTC, wlechowicz commented on pages/api/mylist/[movieId].js
> +    if (Number.isInteger(id) && id > 0) {
Duplicated. Also should be at the very top of the handler - input params validation comes first, if `id` isn't legit then why fetch data from DB etc. If `id` is bad, return 400.

2022-03-28 23:44 UTC, wlechowicz commented on pages/api/mylist/[movieId].js
> +        return res.status(200).json();
This if and the else to the same exact thing.

2022-03-29 00:29 UTC, rast-mk1 commented on app/server/services/myListClient.js
> +  }
Meaning, that movie with given id exists in theMovieDB?

2022-03-29 22:24 UTC, wlechowicz requested changes

2022-03-29 22:24 UTC, wlechowicz commented on app/server/services/myListClient.js
> +    return;
`return [];` because it will be used not only through endpoint by from server-side component code as well.

2022-03-29 22:24 UTC, wlechowicz commented on pages/api/mylist/[movieId].js
> +  }
```suggestion
  const method = req.method.toLowerCase();
  if (!['put', 'delete'].includes(method)) {
    return res.status(405).send();
  }
```
and use `method` in the `if`s later on, for consistency.

2022-03-29 22:54 UTC, wlechowicz approved these changes

2022-03-29 23:01 UTC, merged