feat:  user action menu #1729
intive/patronage22_poznan_js pull request #95
Opened 2022-03-27 12:41 UTC by wolnio

2022-03-29 20:07 UTC, weronika299 requested changes

2022-03-29 20:07 UTC, weronika299 commented on app/components/ActionMenu/index.js
> +import { useSession as useSessionActual } from 'next-auth/react';
I think that this import (line 3) should be the first on the list.

2022-03-29 22:17 UTC, wlechowicz requested changes
This menu will be controlled by Header, so rather than ActionMenu using useSession, it should accept `user` object in props, that will get passed down from Header.
You can use modal to showcase feature in Storybook, but not in the actual component, because there already is a real modal on the page.

2022-03-29 22:17 UTC, wlechowicz commented on app/components/ActionMenu/index.js
> +              <UserAvatar size={100} />
You need to pass in `avatar` prop, avatar is blank otherwise.

2022-03-29 22:17 UTC, wlechowicz commented on app/components/ActionMenu/ActionMenu.styles.js
> +  height: 100%;
100% of what? The outer-most element shouldn't have a set height - instead, it's the content+paddings+margins that will determine its height from inside naturally.

2022-03-29 22:17 UTC, wlechowicz commented on app/components/ActionMenu/ActionMenu.styles.js
> +  .username {
Unexpected use of classes. Use a separate styled component instead.

2022-03-29 22:17 UTC, wlechowicz commented on app/components/ActionMenu/ActionMenu.styles.js
> +const ActionList = styled.ul`
`ul` should have list items `li` inside, you have just buttons. If you want to have this as a list (which isn't a bad idea) then you need to wrap buttons in list items.

2022-03-29 22:17 UTC, wlechowicz commented on app/components/ActionMenu/index.js
> +        {isModalOpen && <Modal content={content} />}
Modal cannot be a part of this component.

2022-03-29 22:17 UTC, wlechowicz commented on app/components/ActionMenu/index.js
> +export default function ActionMenu({ isOpen, useSession = useSessionActual }) {
`isOpen` is not used. Accept `user` as prop instead of using session.
Use existing `openModal` action from app actions, you can mock it in story template (use isModalOpen in story Template to show a modal).

2022-03-29 22:17 UTC, wlechowicz commented on app/components/ActionMenu/index.js
> +  const { isModalOpen, content } = state;
Use this only in story for presentation, not in the component itself.

2022-03-29 22:17 UTC, wlechowicz commented on app/components/ActionMenu/index.js
> +        <Button fullWidth href="#">
`onClick={signOut}` Check app\components\Account\index.js for reference.

2022-03-30 21:32 UTC, wolnio commented on app/components/ActionMenu/index.js
> +export default function ActionMenu({ isOpen, useSession = useSessionActual }) {
Do you mean to create separate story where isModalOpen is set to true so modal is already open when we open that story?

2022-03-30 22:12 UTC, wlechowicz approved these changes

2022-03-30 22:15 UTC, wlechowicz commented on app/components/ActionMenu/index.js
> +export default function ActionMenu({ isOpen, useSession = useSessionActual }) {
I meant you could make a story where you put the menu on the left and the modal opens with "Account" when you press the Account button in your menu. To do that, the story Template component would have to host the modal like app does and the action from menu would open that modal. Not worth IMO since it's not testing the account, but just the button.

2022-03-30 22:23 UTC, weronika299 approved these changes

2022-03-30 22:34 UTC, wlechowicz commented
One more request, make the menu usable - make it open and close from the Header.
Opens when user avatar in Header is clicked (make Header's UserAvatar a button) and closes either when avatar is clicked again or with a useOnClickOutside hook for a click outside of the menu container.

2022-03-30 22:39 UTC, weronika299 commented on app/components/ActionMenu/index.js
> +import { signOut } from 'next-auth/react';
One more thing, It could be first on the list.

2022-04-02 21:08 UTC, hiimsagan approved these changes

2022-04-05 13:54 UTC, marcelina-hasiak commented
Looks good for me too. Only one thing you need to adjust is Header story.
<img width="300" alt="Zrzut ekranu 2022-04-5 o 15 51 55" src="https://user-images.githubusercontent.com/62512837/161769724-e7b3c406-bda6-492a-8fa4-56f48ffd98e2.png">

2022-04-06 18:16 UTC, merged