feat: Home page #1728
intive/patronage22_poznan_js pull request #96
Opened 2022-03-27 13:14 UTC by weronika299

2022-03-27 19:45 UTC, wolnio requested changes

2022-03-27 19:45 UTC, wolnio commented on app/components/Pages/HomePage/HomePage.styles.js
> +  height: 0;
Positioning of a header looks strange. At the end you get what you want, but the text isn't even in the scope of it's container - it can be easily seen on the image below, text is inside of it's padding. I don't think `height: 0` for text field is good solution. It's good to remember that headers h1 - h6 have build in `margin top and bottom`. For h5 margin equals to something around `1.67em`.
![image](https://user-images.githubusercontent.com/28785400/160297570-2a2d9d4f-622a-401f-aa51-50ac119a8f61.png)

2022-03-27 20:39 UTC, weronika299 commented on app/components/Pages/HomePage/HomePage.styles.js
> +  height: 0;
Yes, I will change this to positioning  of each CarouselWrapper. Thanks!

2022-03-27 20:43 UTC, rast-mk1 requested changes
For some reason, footer is gone and OpenModal button is there instead.
![obraz](https://user-images.githubusercontent.com/56893415/160300157-059ea7ab-5df4-4a9c-a09c-cec5eb8e869a.png)
Also, you could add padding around MovieCard or make background transparent.

2022-03-27 21:20 UTC, wlechowicz requested changes
Grey background behind MovieCard shouldn't be there, but that's probably Carousel bug. Movie title in carousels should be left aligned, not centered - that's probably a MovieCard bug.

2022-03-27 21:20 UTC, wlechowicz commented on pages/index.js
> +      {isModalOpen && <Modal content={content} />}
Delete this please.

2022-03-27 21:20 UTC, wlechowicz commented on pages/index.js
> +    const chosenMovieId = listOfHeroMoviesId[Math.floor(Math.random() * listOfHeroMoviesId.length)];
I'd call it `randomMovieId`

2022-03-27 21:20 UTC, wlechowicz commented on pages/index.js
> +        pageLayout: { header: true, footer: false },
Let's have the footer on, this is the page that user will spend most of their time on (apart from the player, of course).

2022-03-27 21:20 UTC, wlechowicz commented on pages/index.js
> +    let listOfCategories = await Promise.all(
Make this a const, and then instead of unshifting popular list onto this, return it as `[popularCategory, ...listOfCategories]`.

2022-03-27 21:20 UTC, wlechowicz commented on package.json
> +    "promise": "^8.1.0",
Nope.

2022-03-27 21:20 UTC, wlechowicz commented on app/components/Pages/HomePage/index.js
> +import Link from 'next/link';
Imports from outside of our app (packages etc.) should be the first on the list, then out own imports. Move this to the top.

2022-03-27 21:20 UTC, wlechowicz commented on app/components/Pages/HomePage/index.js
> +            <Link href="/#" passHref>
Please use correct links for this and the movie card. This would be `/category/${id}`

2022-03-27 21:20 UTC, wlechowicz commented on app/components/Pages/HomePage/index.js
> +        {listOfCategories.map((list) => (
Destructure props from `list` here.

2022-03-27 21:20 UTC, wlechowicz commented on app/components/Pages/HomePage/index.js
> +      <CarouselWrapper>
Carousels are left-aligned, should be centered.

2022-03-27 21:20 UTC, wlechowicz commented on app/components/Carousel/index.js
> +            src={images?.poster?.original}
MovieCard should not be using the original image size, but a smaller one, like M or L.

2022-03-27 21:20 UTC, wlechowicz commented on app/components/Carousel/index.js
> +  const CarouselItem = ({ tileCount, src, title, movieId }) => (
```suggestion
  const CarouselItem = ({ tileCount, ...props }) => (
```

2022-03-27 21:20 UTC, wlechowicz commented on app/components/Carousel/index.js
> +        <MovieCard src={src} title={title} movieId={movieId} />
```suggestion
        <MovieCard {...props} />
```

2022-03-27 21:48 UTC, wlechowicz commented on pages/index.js
> +    const listOfHeroMoviesId = [508947, 634649, 696806, 568124, 414906];
I just had this idea that, instead of this being a random movie out of a list of hand-piked movies, it would be cool if it was a random movie from the 10 most popular movies -  you have the popular list here already, so it should be easy, like `const randomIdFromMostPopularTop10 = popularList[Math.floor(Math.random() * Math.min(10, popularList.length)]`.
This way the possible heroes will change over time and will stay relevant.

2022-03-27 22:03 UTC, wlechowicz commented on app/components/UI/MovieCard/MovieCard.styles.js
> +  aspect-ratio: 1 / 1.8;
This is added to the wrong element. It's on the whole wrapper instead of only the poster image (PoterWrapper). It makes the active area of the `a` extend down below the title element.
Then, 1.8 denominator is too much and it makes the image too narrow, clipping titles. `1 / 1.5` seems to be the sweet spot.

2022-03-28 10:36 UTC, weronika299 commented on pages/index.js
> +        pageLayout: { header: true, footer: false },
Okay but this is our old footer that we used before design, so should i change the old footer to the new one (does the new one only have height and color?) in the footer component and then make it visible?

2022-03-28 12:47 UTC, rast-mk1 requested changes
When you press chevron to get another portion of movies from Carousel, images are not loaded yet. Need to load remaining images before user clicks chevron. Also, images that are on first slide are still loading when page is rendered.

2022-03-28 13:11 UTC, weronika299 commented
> When you press chevron to get another portion of movies from Carousel, images are not loaded yet. Need to load remaining images before user clicks chevron. Also, images that are on first slide are still loading when page is rendered. EDIT: inside `MoviePoster` component, there is `blurDataURL={'images/placeholder-blur.png'}` that should blur images, when loading. It used to work fine when I tested it, but now it doesn't. I will try to look into that.

2022-03-28 14:19 UTC, wlechowicz commented on pages/index.js
> +        pageLayout: { header: true, footer: false },
Keep the footer as is, changing it is not in the scope of this story.

2022-03-28 16:20 UTC, weronika299 commented on pages/index.js
> +        pageLayout: { header: true, footer: false },
Okay :)

2022-03-28 16:34 UTC, wlechowicz commented
> When you press chevron to get another portion of movies from Carousel, images are not loaded yet. Need to load remaining images before user clicks chevron. Also, images that are on first slide are still loading when page is rendered. EDIT: inside `MoviePoster` component, there is `blurDataURL={'images/placeholder-blur.png'}` that should blur images, when loading. It used to work fine when I tested it, but now it doesn't. I will try to look into that.

The images loading in late is the behavior of next/image as it doesn't preload images that aren't visible. It's a good optimization since we don't need to load in all of the 100+ images in the page at once. Changing the image used from original size poster to a smaller image should greatly help the load ins.

2022-03-29 16:03 UTC, marcelina-hasiak requested changes
Some little suggestions from my side. 
Apart from that I really like the outcome :) Good job!!!

2022-03-29 16:03 UTC, marcelina-hasiak commented on pages/index.js
> +      resultsOfPopularList[Math.floor(Math.random() * Math.min(10, resultsOfPopularList.length))]
I would move this math operation to utils folder and wrap with function. It seems to me we have plenty of Math.blablabla and some of them maybe we can reuse in the future. Not to mention it would be nicer to read the code here.

2022-03-29 19:47 UTC, weronika299 commented on app/components/Pages/HomePage/HomePage.styles.js
> +`;
Yes, we have already 'to do' tasks on Jira.

2022-03-29 21:17 UTC, wlechowicz commented on pages/index.js
> +      resultsOfPopularList[Math.floor(Math.random() * Math.min(10, resultsOfPopularList.length))]
I'd drop a comment on line 37 to explain what it does, but it won't be used anywhere else so let it sit here.

2022-03-29 21:18 UTC, wlechowicz commented on app/components/UI/MovieCard/index.js
> +export default function MovieCard({ ...props }) {
If anything, it should be `MovieCard({ movie })` since it's kinda stupid to pass props one by one when they come from the same object.

2022-03-29 21:26 UTC, wlechowicz approved these changes
Minor issues discussed in Marcelina's review. One improvement that would make it nicer would be if the header was being hidden with an animation, rather than this BAM gone BAM visible.

Overall very nice, Let's get this in.

2022-03-29 23:34 UTC, rast-mk1 approved these changes

2022-03-29 23:35 UTC, rast-mk1 commented
Starting to look like a real thing :)

2022-03-30 11:33 UTC, weronika299 commented on app/components/UI/MovieCard/index.js
> +export default function MovieCard({ ...props }) {
So is my solution also correct or should it be changed?

2022-03-30 11:35 UTC, weronika299 commented on app/components/Header/index.js
> +        <NavigationBar remove={remove}>
This prop is unnecessary. I think I forgot to delete it after trying a different solution.

2022-03-30 14:54 UTC, marcelina-hasiak commented on app/components/UI/MovieCard/index.js
> +export default function MovieCard({ ...props }) {
Of course it is correct. We just use destructure where it's possible to minimize amount of code and maximize readability.

2022-03-30 18:09 UTC, marcelina-hasiak approved these changes

2022-03-30 19:02 UTC, wlechowicz approved these changes

2022-03-30 19:37 UTC, wlechowicz commented
Let's get this in.

2022-03-30 20:29 UTC, wlechowicz commented
Dismissing one stale review in light of the owner not being active. You can merge.

2022-03-30 21:30 UTC, merged