fix: authcontainer backgroud size #1784
intive/patronage22_poznan_js pull request #97
Opened 2022-03-28 21:22 UTC by weronika299

2022-03-28 22:02 UTC, wlechowicz requested changes
- blur doesn't seem to work
- you shouldn't need to set blurDataUrl manually to files that we host statically, Image should do it itself (https://nextjs.org/docs/api-reference/next/image#placeholder)
- you might have to `import` the image like this https://nextjs.org/docs/basic-features/image-optimization#local-images
- the new image is 1.1 MB yet the quality on the page is poor due to Image applying optimizations I assume. Default `quality` is 75, try setting it to 90 - 100.

2022-03-28 23:33 UTC, rast-mk1 commented
> * blur doesn't seem to work
Actually, it does work: 
![obraz](https://user-images.githubusercontent.com/56893415/160503952-b55c1ac6-dfe4-47da-8c3a-9d0c76bf9b53.png)

2022-03-28 23:43 UTC, rast-mk1 commented on app/components/Pages/AuthPageContainer/index.js
> +        blurDataURL={'/images/blur-auth-placeholder.png'}
You don't really need `blurDataURL` for your purpose, but if you want to use it, image should be much smaller

> It will be enlarged and blurred, so a very small image (10px or less) is recommended. 

You could use `public/images/placeholder-blur.png` for that.

2022-03-29 16:57 UTC, marcelina-hasiak requested changes

2022-03-29 16:57 UTC, marcelina-hasiak commented on app/components/Pages/AuthPageContainer/AuthPageContainer.styles.js
> +  ${device.tablet} {
device.mobile ?

2022-03-29 16:57 UTC, marcelina-hasiak commented on app/components/Pages/AuthPageContainer/index.js
> +        blurDataURL={'/images/blur-auth-placeholder.png'}
and 615kb for placeholder - I think it's still too heavy

2022-03-29 19:36 UTC, weronika299 commented on app/components/Pages/AuthPageContainer/AuthPageContainer.styles.js
> +  ${device.tablet} {
Why?

2022-03-29 19:48 UTC, marcelina-hasiak commented on app/components/Pages/AuthPageContainer/AuthPageContainer.styles.js
> +  ${device.tablet} {
I have desktop first approach at my job and I forgot we've got here just the opposite; sorry for mixing it up ;)

2022-03-29 19:55 UTC, marcelina-hasiak approved these changes

2022-03-29 19:57 UTC, marcelina-hasiak commented
I approved PR but I forgot  to add that I couldn't recreate blur image on storybook. Is it already fixed?

2022-03-29 20:15 UTC, weronika299 commented
> I approved PR but I forgot to add that I couldn't recreate blur image on storybook. Is it already fixed?

Unfortunately I haven't fixed it yet. :/

2022-03-29 21:14 UTC, wlechowicz approved these changes
Works well with throttled network and disabled cache. If blur doesn't work in Storybook, well too bad for Storybook.

2022-03-29 21:22 UTC, rast-mk1 approved these changes

2022-03-29 21:58 UTC, merged