Feature/p2022 1485 category page
intive/patronage22_poznan_js pull request #99
Opened 2022-03-30 07:42 UTC by lenasokolova

Have some issues when trying to search through the retrieved movies on page. 
TypeError: Cannot read properties of undefined (reading 'value').
![image](https://user-images.githubusercontent.com/62836941/160777256-8094e82f-614f-42ab-8bb2-6e39d2e2bd2f.png)

Unfortunately, media queries don't work properly and I can't find where the problem is. It overwrites the basic styles for WrapperGrid, there are 3 columns on responsive instead of 5 as a basic style is. I've tried it with column-count and grid-template-columns properties.

2022-03-30 13:50 UTC, wlechowicz commented
> Unfortunately, media queries don't work properly and I can't find where the problem is.

I believe they do work properly, you're just not sure about the order. Mobile-first means:
```
export const WrapperGrid = styled.div`
  // any rules defined here apply to mobile and bigger (mobile, tablet, desktop)

  ${device.tablet} {
    // any rules here apply to tablet and bigger (tablet, desktop), overriding mobile rules
  } 

  ${device.desktop} {
    // any rules here apply to desktop and bigger, overriding mobile and tablet rules
  }
`;
```

2022-03-30 23:24 UTC, rast-mk1 requested changes
While on `/category/id` page, header elements are unclickable.

2022-03-31 20:09 UTC, weronika299 requested changes
I noticed that our category page for popular movies returns  ''oops, looks like there are no movies in this category'' is it ok?

2022-03-31 20:10 UTC, rast-mk1 commented on app/components/Pages/CategoryPage/CategoryPage.js
> +          </MovieCardWrapper>
Hrefs for movies are `movie/undefined`.

2022-03-31 20:35 UTC, lenasokolova commented on pages/category/[id].js
> +    <div>
right, it doesn't serve any purpose

2022-03-31 21:17 UTC, wlechowicz requested changes

2022-03-31 21:17 UTC, wlechowicz commented on app/components/Pages/CategoryPage/index.js
> +          <MovieCardWrapper key={id}>
Calling an index an `id` doesn't stop it from being the array's index ;)
```suggestion
        {filteredList.map((film) => (
          <MovieCardWrapper key={film.id}>
```

2022-03-31 21:17 UTC, wlechowicz commented on app/components/Pages/CategoryPage/index.js
> +              {...props}
Are the rest of the props necessary? It's an empty object.

2022-03-31 21:17 UTC, wlechowicz commented on app/components/Pages/CategoryPage/index.js
> +  const [searchQ, setSearchQ] = useState('');
> React Hook "useState" is called conditionally. React Hooks must be called in the exact same order in every component render.eslint[react-hooks/rules-of-hooks](https://reactjs.org/docs/hooks-rules.html)

Seems your ESLint isn't working. Hooks cannot be used conditionally, which means you can't have any conditional return before using hooks. You need to move the ErrorWrapper logic below useState.

2022-03-31 21:17 UTC, wlechowicz commented on app/components/Pages/CategoryPage/index.js
> +              href={`/movie/${props.id}`}
```suggestion
              href={`/movies/${film.id}`}
```

2022-03-31 22:14 UTC, lenasokolova commented on app/components/Pages/CategoryPage/index.js
> +          <MovieCardWrapper key={id}>
ok, now I see, I was trying to put `film.id` in `{filteredList.map((film, film.id) => (` and it said there's a mistaken syntax... I thought I have to pass it first as a parameter before putting in a key. My bad.

2022-04-06 11:08 UTC, weronika299 approved these changes

2022-04-06 18:15 UTC, wlechowicz approved these changes
Looks good.
Final cosmetic change would be to set the page container at `min-height: 100vh;` because now a white bottom is showing if the list is short.
![obraz](https://user-images.githubusercontent.com/24250766/162041256-00249dd9-ec96-4674-bc12-f5579f85a950.png)

2022-04-07 00:43 UTC, rast-mk1 approved these changes

2022-04-07 11:53 UTC, marcelina-hasiak approved these changes

2022-04-07 15:09 UTC, merged